### ISSUE TITLE
Firebase signIn with OIDC and signInWithRedirect

### ISSUE THREAD

**Issue by 5tructAndFunc** [google/mesop#1002]
Hi everyone,

based on [this](https://github.com/google/mesop/tree/1f34f5669ba2ab064d91a6e11e1da5848bf92077/mesop/examples/web_component/firebase_auth) example, I am trying to build a web component, that will add a single sign on function to our mesop Application and at the same time allow us to get information about the signed in user.  We would like to use the signIn with redirect functionality provided by firebase auth. I am following the best practices described [here](https://firebase.google.com/docs/auth/web/redirect-best-practices).
While `signInWithRedirect` does the job (we are able to see the HTTP requests required for the OAUTH code flow in the browsers Dev Tools), `getRedirectResult` always returns `null`, which according to the docs means, that the `signInWithRedirect` was not successfull. 

Are we missing something here? 

**To Reproduce**

I tried to extract the relevant parts of the source code that we use in our "firebase_auth_component.js": 

```
let firebaseConfig = {
    authDomain: '<custom_domain_name>',
    projectId: '<projectId>',
}

 connectedCallback() {
        super.connectedCallback();
        firebaseConfig.apiKey = this.key // comes in as a parameter to this component
        const provider = new OAuthProvider('<provider_configured_in_firebase_console>')

        const app = initializeApp(firebaseConfig);
        const auth = getAuth();

        getRedirectResult(auth).then(result => {
            if (!!!result) {
                setPersistence(auth, browserSessionPersistence)
                    .then(() => {
                        signInWithRedirect(auth, provider).catch((error) => { console.log(error) });
                    })
                    .catch((error) => {
                        // Handle Errors here.
                        var errorCode = error.code;
                        var errorMessage = error.message;
                    });
            }
        }).catch(console.error)
    }

    firstUpdated() {
        let auth = getAuth()

        onAuthStateChanged(auth, (user) => {
            getRedirectResult(auth).then(result => {
                if (!!result) {
                    //Get the OAuth access token and ID Token
                    const credential = OAuthProvider.credentialFromResult(result);
                    const accessToken = credential.accessToken;
                    const idToken = credential.idToken;

                    this.dispatchEvent(new MesopEvent(this.authChanged, idToken));
                }
            }).catch(console.error)
        })
    }
```

**Expected behavior**
`getRedirectResult` should return the logged in user.

**Additional context**
We use mesop 0.12.4 and firebase 10.13.2

**Comment by richard-to** [comment]
I have not tried firebase auth yet myself. But I think there is this issue here that details a similar problem: https://github.com/google/mesop/issues/713.

The solution we proposed is to mount Mesop with a FastAPI server. Then use the FastAPI server to handle the login redirect. It's not ideal and will require more work to pass that information between Fast API  and Mesop and vice versa.

**Comment by 5tructAndFunc** [comment]
@richard-to Thank you for your Feedback. 

I am aware of this [thread](https://github.com/google/mesop/issues/713). I have mounted the Mesop app to a FastAPI application. This way, as soon as `signInWithRedirect` is called, I redirect the call to /__/auth/ and this way it is even possible to go through the whole OAUTH code flow. The problem I was referring to actually occurs after the code flow has completed. I was expecting the handler registered in `onAuthStateChanged` to be called so that I can use `getRedirectResult` to ask for the logged in users information. Unfortunately  `getRedirectResult` is responding with `null`.

**Comment by richard-to** [comment]
Thanks for the clarifications. That's very helpful to know. I'll have to take a closer look .

**Comment by 5tructAndFunc** [comment]
@richard-to  @wwwillchen Hi there, today I tried it again. This time, I used your demo example and configured the firebase ui to use `redirect` as `singInFlow`. I am experiencing the same behavior. Every time, when `onAuthStateChanged` is called, the `user` obejct is `null`. Please find attached the whole auth component -- 

```

import { html, LitElement } from 'https://cdn.jsdelivr.net/gh/lit/dist@3/core/lit-core.min.js';
import 'https://www.gstatic.com/firebasejs/10.0.0/firebase-app-compat.js';
import 'https://www.gstatic.com/firebasejs/10.0.0/firebase-auth-compat.js';
import 'https://www.gstatic.com/firebasejs/ui/6.1.0/firebase-ui-auth.js';

let ui = null

const uiConfig = {
    signInSuccessUrl: '/firebase_auth/firebase_auth_app',
    signInFlow: 'redirect',
    signInOptions: ['<custom_oidc_provider_id>'],
    tosUrl: '<custom_domain>',
    // Privacy policy url/callback.
    privacyPolicyUrl: () => {
        window.location.assign('<your-privacy-policy-url>');
    },
};

class FirebaseAuthComponent extends LitElement {
    static properties = {
        isSignedIn: { type: Boolean },
        authChanged: { type: String },
    };

    constructor() {
        super();
        this.isSignedIn = false;
    }

    createRenderRoot() {
        // Render in light DOM so firebase-ui-auth works.
        let firebaseConfig = {
            authDomain: '<custom_domain>',
            projectId: '<firebase_project_id>',
        };
        firebaseConfig.apiKey = this.key
        firebase.initializeApp(firebaseConfig);

        // Initialize the FirebaseUI Widget using Firebase.
        ui = new firebaseui.auth.AuthUI(firebase.auth());

        return this;
    }

    firstUpdated() {
        firebase.auth().onAuthStateChanged(
            async (user) => {
                if (user) {
                    this.isSignedIn = true;
                    const token = await user.getIdToken();
                    this.dispatchEvent(new MesopEvent(this.authChanged, token));
                } else {
                    this.isSignedIn = false;
                    this.dispatchEvent(new MesopEvent(this.authChanged, ''));
                }
            },
            (error) => {
                console.log(error);
            },
        );

        ui.start('#firebaseui-auth-container', uiConfig);
    }

    signOut() {
        firebase.auth().signOut();
    }

    render() {
        return html`
      <div
        id="firebaseui-auth-container"
        style="${this.isSignedIn ? 'display: none' : ''}"
      ></div>
      <div
        class="firebaseui-container firebaseui-page-provider-sign-in firebaseui-id-page-provider-sign-in firebaseui-use-spinner"
        style="${this.isSignedIn ? '' : 'display: none'}"
      >
        <button
          style="background-color:#ffffff"
          class="firebaseui-idp-button mdl-button mdl-js-button mdl-button--raised firebaseui-idp-google firebaseui-id-idp-button"
          @click="${this.signOut}"
        >
          <span class="firebaseui-idp-text firebaseui-idp-text-long"
            >Sign out</span
          >
        </button>
      </div>
    `;
    }
}

customElements.define('firebase-auth-component', FirebaseAuthComponent);
```

The FastAPI to forward the calls:

```
@app.api_route("/__/auth/{path:path}", methods=["GET"])
async def auth_endpoint_get(request: Request, path: str):
    url = f"https://<project_id>.firebaseapp.com/__/auth/{ path }?{request.query_params}"

    try:
        response = RedirectResponse(
            url=url, status_code=status.HTTP_307_TEMPORARY_REDIRECT
        )

        return response

    except Exception as e:
        return JSONResponse({"error": f"Request failed: {e}"}, status_code=500)
```


Thank you for your efforts. I hope this example helps and I look forward to your feedback.

**Comment by richard-to** [comment]
Just FYI, planning to look closer at this some time this week.

**Comment by richard-to** [comment]
I took a look and I was able to reproduce your issue. Not sure yet what's wrong exactly.

Interestingly if I use the popup flow rather than redirect flow then it does work for me. Maybe you can use the pop up flow temporarily.

I'll look some more later.

On the redirect back to the page I get this loading indicator that never shows anything.

![Image](https://github.com/user-attachments/assets/f40e6654-f0a6-4112-a2d9-b0f5c8cdc578)

**Comment by 5tructAndFunc** [comment]
@richard-to  Thank you for your feedback. 

This is in line with our experience so far. As already mentioned, we used an oidc provider in our tests and were able to see the necessary HTTP requests happening for code flow OAUTH. We may consider using the popup version temporarily, although, from a user experience point of view, the pop up version unfortunately does not fully meet the requirements.

Thank you for your efforts so far and please keep us updated with any news in this regard.

**Comment by richard-to** [comment]
I looked into this a bit more. I think maybe it's due to an issue forwarding the request with Fast API. 

Seems like there's a 302 redirect showing up on the Google auth side. Even though Fast API is doing a 307.

![Image](https://github.com/user-attachments/assets/39e5dcc0-e898-43cd-aa30-9ed095b7a924)

I'm not 100% sure if that is indeed the issue though. Docs mention it can't be done via 302, but the Fast API code is doing 307, so it seems like it should be OK.

> Set up a reverse proxy on your app server so that GET/POST requests to https://<app domain>/__/auth/ are forwarded to https://<project>.firebaseapp.com/__/auth/. Ensure that this forwarding is transparent to the browser; this cannot be done via a 302 Redirect.

I haven't tried using nginx to reverse proxy the request. Was curious what the flow would look like in that scenario.

**Comment by richard-to** [comment]
So I dug a bit further and was able to get it to "work" (though there is some odd UX with how the iframe reloads).

Here's an updated version of the handler. Instead of doing a redirect, the handler will make a request to the app's firebase domain and return the response.

I'm using httpx lib, but you can use whatever you want (requests or urllib should also work)

```python
@app.api_route("/__/auth/{path:path}", methods=["GET", "POST"])
async def proxy(request: Request, path: str):
    # Construct the upstream URL by appending the path from the client request
    url = f"https://<your-app>.firebaseapp.com/__/auth/{ path }?{request.query_params}"

    # Get the method (GET, POST, etc.)
    method = request.method

    # Get headers from the incoming request
    headers = dict(request.headers)

    if method == "POST":
        body = await request.body()
    else:
        body = None

    # Create a request to the upstream server using httpx
    async with httpx.AsyncClient() as client:
        response = await client.request(method, url, headers=headers, content=body)

    return Response(response.text.strip(), response.status_code)
```

One issue that took me a bit to realize was that I also needed to set the redirect uri for my domain in the GCP OAuth 2.0 Client that gets created automatically for Firebase.

This can be found at https://console.cloud.google.com/apis/credentials. It should be at the "OAuth 2.0 Client IDs" section. Then go to the "Authorized redirect URIs" section.

**Comment by richard-to** [comment]
Closing this issue. No response in a couple weeks, so assuming this issue is resolved now.

**Comment by 5tructAndFunc** [comment]
Hi @richard-to , sorry for my late reply. Unfortunately I haven't had the chance to test your suggestionen yet. I will definitely give it a try, as soon as I get the chance / time for it. For now, thank you very much for your efforts and for the feedback.

**Comment by 5tructAndFunc** [comment]
> So I dug a bit further and was able to get it to "work" (though there is some odd UX with how the iframe reloads -- I think actually the UX issue is because I had some test code I forgot to remove).
> 
> Here's an updated version of the handler. Instead of doing a redirect, the handler will make a request to the app's firebase domain and return the response.
> 
> I'm using httpx lib, but you can use whatever you want (requests or urllib should also work)
> 
> @app.api_route("/__/auth/{path:path}", methods=["GET", "POST"])
> async def proxy(request: Request, path: str):
>     # Construct the upstream URL by appending the path from the client request
>     url = f"https://<your-app>.firebaseapp.com/__/auth/{ path }?{request.query_params}"
> 
>     # Get the method (GET, POST, etc.)
>     method = request.method
> 
>     # Get headers from the incoming request
>     headers = dict(request.headers)
> 
>     if method == "POST":
>         body = await request.body()
>     else:
>         body = None
> 
>     # Create a request to the upstream server using httpx
>     async with httpx.AsyncClient() as client:
>         response = await client.request(method, url, headers=headers, content=body)
> 
>     return Response(response.text.strip(), response.status_code)
> One issue that took me a bit to realize was that I also needed to set the redirect uri for my domain in the GCP OAuth 2.0 Client that gets created automatically for Firebase.
> 
> This can be found at https://console.cloud.google.com/apis/credentials. It should be at the "OAuth 2.0 Client IDs" section. Then go to the "Authorized redirect URIs" section.

@richard-to   I finally had the chance to test your latest suggestions. Authentication with redirect works for us now. Thanks a lot for your support.
