### ISSUE TITLE
App Engine response buffering causes SSEs to be buffered

### ISSUE THREAD

**Issue by richard-to** [google/mesop#1005]
Not technically a bug.

See https://cloud.google.com/appengine/docs/flexible/how-requests-are-handled?tab=python#x-accel-buffering

Apparently this can be disabled if using `X-Accel-Buffering=no` in the response.

Not really sure yet how to handle this since this is App Engine specific, so not sure we want to set this every time.

We could have a flag / config / env var that disables it (could be too specific)

Alternatively add a way for people to adjust the header response (this could be too broad)

**Comment by richard-to** [comment]
Maybe a temporary workaround is to use nginx in front of Mesop. Then I believe you can use nginx to modify the response header. I think the main thing is making a Docker image that has both nginx and Mesop installed.

**Comment by wwwillchen** [comment]
Interesting, good find!

I did a bit of Googling and it looks like this setting isn't App-engine specific and it's from [nginx](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#:~:text=%E2%80%9CX%2DAccel%2DBuffering%E2%80%9D%20enables%20or%20disables%20buffering%20of%20a%20response%3B)

I'm inclined to just setting `X-Accel-Buffering=no` in all the (SSE) UI responses.
