### ISSUE TITLE
Timer component

### ISSUE THREAD

**Issue by davorinrusevljan** [google/mesop#1016]
from app point of view, it would be nice to have Timer component, ideally invisible, that would fire up some Mesop event after some time has passed.

**Comment by richard-to** [comment]
You can probably implement a web component to do this. It's not exactly what you're asking for but we have an example web component called "async action" here: https://github.com/google/mesop/tree/main/mesop/examples/web_component/async_action

**Comment by davorinrusevljan** [comment]
Thank you for pointing me in direction, I should be able to cobble something up with this.
