### ISSUE TITLE
Uploader

### ISSUE THREAD

**Issue by raphsaeed** [google/mesop#1031]
**Describe the bug**
On the Chrome browser, uploader does not upload the file with same name again, in the same folder, even if the contents of file or size is different and configured to over-write existing file.

**To Reproduce**
go to following link in chrome
https://google.github.io/mesop/components/uploader/
Upload an image file.... SUCCESS
rename the file something else and chooses another image with the previous file name you uploaded.
Try uploading again......DOES NOT upload

Try same in Safari it works

**Expected behavior**
It should upload the file as expected....

**Screenshots**

**Desktop System Info**

- Browser Chrome, works with safari

**Additional context**

**Comment by richard-to** [comment]
Great catch. I think this should be easy to fix. I'll try to get a fix for this some time this week.

**Comment by raphsaeed** [comment]
Thanks a lot, I really appreciate that. It will make my users happy.

Best Regards
