### ISSUE TITLE
Add Angular Card Component

### ISSUE THREAD

**Issue by richard-to** [google/mesop#1080]
Ref: https://material.angular.io/components/card/examples

Simple component to do, but a nice way for people with less HTML/CSS knowledge to add a common component with a consistent styling and behavior.

**Comment by akhil02hero** [comment]
Hi @richard-to  Can I contribute in this

**Comment by richard-to** [comment]
Hi @akhil02hero. Thanks for your interest. I have a pull request for the card component, so the the general card component is generally done for the time being.

If you're interested in helping add more components to Mesop, it would be very welcome. We still have a bunch of Angular components that we have not added yet. Top of mind is the tab component (https://github.com/google/mesop/issues/93).
