### ISSUE TITLE
Replace localhost with 127.0.0.1 in order to reduce +-300ms of latency

### ISSUE THREAD

**Issue by 444B** [google/mesop#1114]
**Describe the bug**
When using `mesop init` and loading the starter kit, we see the following values
http://localhost:32123/starter_kit := +-300ms
http://127.0.0.1:32123/starter_kit := +-4ms

The reason for this big difference is the unnecessary DNS lookup.

**To Reproduce**

1. create a mesop app (such as with `mesop init`)
2. go to the links above and view via developer network tab
3. Compare "Connection Start" values

**Expected behavior**
This is working as designed. I suppose this issue is more of a suggestion for Performance Engineering. You can change the Label if you agree.

**Screenshots**

**Desktop System Info**
N/A, replicable from multiple machines

**Additional context**
[Random article](https://medium.com/hackernoon/how-changing-localhost-to-127-0-0-1-sped-up-my-test-suite-by-1-800-8143ce770736) describing performance improvements by moving to IP instead of localhost

**Comment by 444B** [comment]
The way to do this is to alter the serving arguments for flask within mesop

**Comment by wwwillchen** [comment]
I'm a little concerned that some Mesop app developers may need to use localhost, for example, they have custom `/etc/hosts` mappings. I'd be open to having the hostname be set by a CLI flag, so you could set it to 127.0.0.1 or 0.0.0.0 (which may be desirable in some use cases).

I'm also somewhat dubious it's actually 300ms for most use cases - I just tested this on my personal computer and Chrome DevTools reported the DNS lookup time at 10 microseconds (Chrome has a DNS cache)
