### ISSUE TITLE
Event handlers are not pulling the latest state

### ISSUE THREAD

**Issue by nirben82** [google/mesop#1150]
**Describe the bug**
When setting `MESOP_WEB_SOCKETS_ENABLED=true`, event handlers might not pull the latest state.

**To Reproduce**
When `thread_id` is generate with this code, `log.info(state.thread_id)` logs `''`, which is the previous value of thread_id in State.

```
def on_load_main(e: me.LoadEvent):
  state = me.state(State)
  state.thread_id = ''
  me.set_theme_mode("system")

def on_click_start_conversation(e: me.ClickEvent):
  state = me.state(State)
  state.thread_id = str(uuid.uuid4())
  yield
  yield from _submit_chat_msg()

def on_click_stop_conversation(e: me.ClickEvent):   ## button is clicked while the `on_click_start_conversation` is still yielding elements.
  state = me.state(State)
  log.info(state.thread_id)
  ...
```

My workaround is to set thread_id value in `on_load_main`, but probably worth understanding if this is an issue.

**Expected behavior**
Event handlers always pull the current state

**Desktop System Info**

- OS: MacOS Sequoia 15.1.1 (24B91)
- Browser: Chrome
- Version: 131

**Comment by wwwillchen** [comment]
Thanks for filing this issue. I made a typo in the docs (fixing in #1151), sorry about that. 

Please set the env var `MESOP_WEBSOCKETS_ENABLED=true` (note: WEBSOCKETS as one word) which will enable websockets.

You should see a log message like this (printed in the terminal):
```
I1217 15:52:58.667261 8582410816 server.py:50] Experiment enabled: MESOP_WEBSOCKETS_ENABLED (auto-enables MESOP_CONCURRENT_UPDATES_ENABLED)
```

Once you have websockets enabled, then the concurrent state access should be fixed.
