### ISSUE TITLE
preventDefault and stopPropagation methods for the select component

### ISSUE THREAD

**Issue by 5tructAndFunc** [google/mesop#1159]
Hi everyone, 

I am using the `select` component in one of our applications. I have noticed that after selecting an option, the page containing the select component is being rerendered. I am working on a use case, where I dont want the page to be rerendered after selecting one of the options in the `select` dropdown. 

1. Is there an Option to prevent this rerendering? something similar to `preventDefault` or `stopPropagation` in JavaScript.
2. If yes, what is the suggested way to do so? 

Thank you for your support

**Comment by wwwillchen** [comment]
How come you want to prevent re-rendering? We don't have any mechanism currently to prevent this.

**Comment by 5tructAndFunc** [comment]
Hi @wwwillchen 

We use the select component to navigate to different pages in the application. After the user selects a page to navigate to, we would like to prevent the page from rendering again before navigating to the next page.
