### ISSUE TITLE
Support responsive design with media query

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#123]

**Comment by richard-to** [comment]
I agree. Being able to support mobile is pretty important. I think Nice GUI does some interesting stuff with CSS and has Tailwind Support which I think is interesting (though I don't think Mesop needs Tailwind support).

**Comment by ducan-ne** [comment]
Support class on box component would be nice. It's totally fine for me to use Tailwind cdn https://tailwindcss.com/docs/installation/play-cdn, it's good both in terms of responsive design + layout.
`<script src="https://cdn.tailwindcss.com"></script>`

**Comment by wwwillchen** [comment]
> Support class on box component would be nice. It's totally fine for me to use Tailwind cdn https://tailwindcss.com/docs/installation/play-cdn, it's good both in terms of responsive design + layout. `<script src="https://cdn.tailwindcss.com"></script>`

@ducan-ne do you mind filing a new issue to support Tailwind? Right now, in addition to allowing setting class names on box, we'd also need to support injecting script tags, which is currently not supported in Mesop. Right now Mesop supports styling through https://google.github.io/mesop/api/style/ and now viewport size, and I think this gives you _most_, but not all of the flexibility that Tailwind provides.

**Comment by ducan-ne** [comment]
@wwwillchen just created a new one #438
