### ISSUE TITLE
Component tree diffs breaks hot reloading

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#187]
When I run without tree diffs, hot reloading works as expected:

```sh
$ ibazel run //mesop/cli -- --path="mesop/mesop/example_index.py" --noenable_component_tree_diffs
```

But when tree diffs are enabled, hot reloading doesn't work:

```sh
$ ibazel run //mesop/cli -- --path="mesop/mesop/example_index.py"
```

Haven't had a chance to look further

**Comment by richard-to** [comment]
Thanks for pointing that out. I'll take a look when I get a chance.

**Comment by wwwillchen** [comment]
Fixed in https://github.com/google/mesop/pull/193
