### ISSUE TITLE
Hot reloading not working for files in demo folder

### ISSUE THREAD

**Issue by richard-to** [google/mesop#248]
If I make changes to a file a in the demo folder, the Mesop app breaks and I need to restart the CLI again.

I think the issue is because the demo folder isn't really covered in execute_module.py since it's not in the mesop directory. Haven't looked at it too much more yet.

It seems like it's not able to load any pages: `User Error: Accessed path: /embed/llm_playground not registered`

**Comment by wwwillchen** [comment]
Yeah, the way I got the demo imports working for the Bazel CLI was quite hacky: https://github.com/google/mesop/blob/d97cd21c97bd7172d4a0d7831aac7ae65b98eebe/demo/main.py#L12

Using the `mesop` pip CLI for the demo directory works w/ hot reload though.

**Comment by richard-to** [comment]
Hmm, yeah that sounds like a reasonable workaround for now.
