### ISSUE TITLE
Preview pane in Demo App can be a bit too thin for more involved examples

### ISSUE THREAD

**Issue by richard-to** [google/mesop#251]
Specifically markdown editor and LLM Playground look a bit too squished in preview mode, especially the latter.

A couple options:

1. Add way to minimize/maximize the code example pane
2. Add a button to expand the embed preview into a full width modal pane
3. Could also add link to the preview outside of the demo app index

For simplicity, probably option 1 seems sufficient.

I think option 3 may not work for some of the current use cases of the demo app where embed it. Option 2 seems a bit weird from a UX perspective (but I guess it'd work similar to say full screen view of a YouTube video UX pattern).

# Example screenshots:

<img width="1311" alt="Screenshot 2024-05-14 at 8 29 33 PM" src="https://github.com/google/mesop/assets/539889/aa78075f-1662-45d7-a29c-559cd62abe71">

<img width="1307" alt="Screenshot 2024-05-14 at 8 29 40 PM" src="https://github.com/google/mesop/assets/539889/dffba2d3-8ecc-43d5-8314-b15fbef3253b">

**Comment by wwwillchen** [comment]
Good points. Re: 3) if you do a link and make it <a href="..." target="_blank">, it will open the link in a new tab, even if the Mesop is embedded in an iframe. I think a combo of #1 and #3 would be good.

We could also try to do a resize bar, like we do for the Editor/DevTools (https://github.com/google/mesop/blob/d0b3e286d0dd9de49eb1d5e3bbc1ab84e96a6d08/mesop/web/src/editor/editor.ts#L90), but it's not very obvious how we translate this into a Mesop/Python API

**Comment by richard-to** [comment]
I see. I didn't realize we could do a target blank link in Mesop. But yeah that would be nice.
