### ISSUE TITLE
Create a way for Mesop app developers to write tests

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#297]
Although we use Playwright internally for framework development, there isn't an easy way to write tests for Mesop apps today.

**Comment by richard-to** [comment]
I think app developers can just use Playwright. Seems like it should be a similar set up. Just the command would be different.

Or are you suggesting that we should have other levels of testing support for Mesop apps?

**Comment by wwwillchen** [comment]
That's fair, outside of Google, using Playwright (or any other testing tool) works. I think having a small example (e.g. in demo) + brief docs on it would be good enough.

I was thinking more about within Google, it's not easy to run Playwright tests, particularly with the rest of internal Google infra, but let's chat about that some more offline since it's specific to Google.
