### ISSUE TITLE
Create patterns examples

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#338]
_This is a good issue for anyone who wants to contribute to Mesop as there's many different patterns we could add to the demo gallery!_

I'm basically calling "pattern" a multi-component examples which demonstrates a common use case.

Ideas:
- Submitting feedback (thumbs up / thumbs down + reasons)
- SxS output rating
- Nav menu
- Header (text)
- Card
- Tile
- Grid tile
- Carousel

**Comment by richard-to** [comment]
Also things like Modal, Accordion, Tab, and Toasts could be useful (until we have the Angular Component equivalents created - Dialog, Tab, Snackbar, etc)

**Comment by iiakshat** [comment]
I was working on the ```submitting feedback``` feature and am unsure if this is how we want to implement it.


![image](https://github.com/google/mesop/assets/92530735/9c3384c0-69a5-4bf3-9dc5-cb8d24d78535)

 If so, I am getting this `error`,
![image](https://github.com/google/mesop/assets/92530735/857f7152-178c-454f-8cd3-e2e16612d658)

Can anyone explain where did I go wrong? 

Here's the colab notebook for reference:
 https://colab.research.google.com/drive/1xma-cG7hcU3vgFjHkZGZK8E2hmGEdn21#scrollTo=hL11Su8HQm9G

**Comment by pranshu-raj-211** [comment]
@iiakshat The issue is in the buttons for feedback
on_click is assigned the lambda function for the func call on_feedback(value), adding a variable made it work for me.

Use this in on_click -  on_click=lambda _: on_feedback(True)

**Comment by richard-to** [comment]
Looks like you resolved your error. When I ran the colab, it seemed ran for me.

-------


One thing to note is that Mesop event handler functions have a non-intuitive behavior if you try to reuse the same function. You should read: https://google.github.io/mesop/guides/interactivity/#avoid-using-closure-variables-in-event-handler

**Comment by srivats22** [comment]
Can anyone contribute to this and add those components??

If so I would also like to have a go at it...

**Comment by richard-to** [comment]
@srivats22, yes, you're right free to contribute any patterns you'd feel would be helpful.

**Comment by srivats22** [comment]
Nice, let me clone the repo and see what I can work on... and will try and get it done
