### ISSUE TITLE
Error running Mesop due to Pandas dep issue

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#345]
From https://news.ycombinator.com/item?id=40575638: 

> The error is: partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)
This happens only on the second interaction.

**Comment by devtombiz** [comment]
Thanks @wwwillchen I made some more tests and I think this error was caused by my local python interpreter in vscode. I switched to python 3.12 and it works correctly now.
Thanks !

**Comment by wwwillchen** [comment]
Got it, thanks!
