### ISSUE TITLE
Create a `mesop deploy` command

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#352]
- It would run the steps in https://google.github.io/mesop/guides/deployment/
- Pre-requisite for checking if gcloud CLI is installed
	- by default uses a file called main.py
	- creates procfile and requirements.txt

**Comment by richard-to** [comment]
Could we also add a way to deploy to App Engine Flex -- gives an easier way to put the app behind auth with IAP compared to Cloud Run where passing the auth token around everywhere can be tedious.

**Comment by wwwillchen** [comment]
Yeah, I think supporting multiple options makes sense.

**Comment by wwwillchen** [comment]
given the diversity of deployment options, I think it's OK to just point people to: https://google.github.io/mesop/guides/deployment/
