### ISSUE TITLE
Support mermaidjs

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#355]
https://github.com/mermaid-js/mermaid
Source: https://www.reddit.com/r/LocalLLaMA/comments/1d8g5j1/comment/l76nrkd/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Could use the upcoming #237 component to support this

**Comment by wwwillchen** [comment]
Should be possible to do this now that #237 and #95 are done.

**Comment by richard-to** [comment]
I added a mermaid example via Markedjs web component integration: https://github.com/google/mesop/pull/667
