### ISSUE TITLE
colab no run

### ISSUE THREAD

**Issue by NickyDark1** [google/mesop#360]
![image](https://github.com/google/mesop/assets/123802672/21f8815c-f74d-47f3-922f-3066ad377c8d)

**Comment by wwwillchen** [comment]
Just double checking, did you run all the cells from top to bottom? Based on the cell execution count, I think you might've skipped executing the first cell (`!pip install mesop`).

**Comment by wwwillchen** [comment]
Closing this, but feel free to re-open if you're still having issues, thanks.
