### ISSUE TITLE
Update grpc-tools to 1.12.4 to support Linux Arm builds

### ISSUE THREAD

**Issue by richard-to** [google/mesop#361]
I was trying to install Mesop for development on Linux (Debian). It kept failing. I tracked it down to this https://github.com/grpc/grpc-node/issues/1405.

I updated the dependency to 1.12.4 and was able to complete the build. Are we allowed to update or do we need to keep that pinned at 1.11.3?

**Comment by wwwillchen** [comment]
I think we can upgrade

**Comment by richard-to** [comment]
One thing I noticed just now is that it seems create this warning message:

```
external/com_google_protobuf_javascript/generator/js_generator.cc:3932:23: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<const google::protobuf::FileDescriptor*>::size_type' {aka 'long unsigned int'} [-Wsign-compare]
 3932 |     for (int i = 0; i < files.size(); i++) {
```
