### ISSUE TITLE
Markdown Video Not Working

### ISSUE THREAD

**Issue by MarcoFerreiraPerson** [google/mesop#373]
Hello,

When attempting to use the following:

```py
me.markdown(
        text="""<video width="40%" height="25%" controls><source src="Miles vs Spider-Man 2099 Epic Fight Scene - Spider-Man Across The Spider-Verse (2023).mp4"></video>"""
    )
```

I am greeted with my video not loading.  

![image](https://github.com/google/mesop/assets/68199617/1cd64e27-aac1-48ef-819b-fd53b97c5a0a)

My video is in the correct path: ```.venv/lib/python3.11/site-packages/mesop/utils/../web/src/app/editor/web_package/videos/Miles vs Spider-Man 2099 Epic Fight Scene - Spider-Man Across The Spider-Verse (2023).mp4'```

I am using ```mesop==0.7.2```

Sorry if I did not give enough information or anything, this is my first time submitting an issue.

Thanks for all of the support!

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by wwwillchen** [comment]
Hi @MarcoFerreiraPerson,

I'd recommend using the [video](https://google.github.io/mesop/components/video/) component instead of the markdown component.

My guess is your video src isn't configured to a valid URL. I'd recommend uploading your video somewhere (e.g. GitHub) and then using that URL.

If you can't do that, you could convert the video into a data URL base-64 encoded, this isn't very performant and I wouldn't recommend it on anything except for small videos:

```py
import base64

def video_to_base64(video_path):
  """
  Converts a video file to a base64 data URL.

  Args:
      video_path: Path to the video file.

  Returns:
      Base64 encoded data URL of the video.
  """
  with open(video_path, "rb") as video_file:
    video_data = video_file.read()
  encoded_data = base64.b64encode(video_data).decode("utf-8")
  data_url = f"data:video/mp4;base64,{encoded_data}"
  return data_url

# Example usage
video_file = "path/to/your/video.mp4"
base64_data_url = video_to_base64(video_file)
print(base64_data_url)
```

**Comment by wwwillchen** [comment]
I'm going to close this issue, but if you're still having issues, please re-open it. Thanks!

**Comment by MarcoFerreiraPerson** [comment]
Hello,

My videos are private and need to be displayed to the user, and then sent over to a remote server. 

I have tried converting the video into base-64 but this is viable since large videos crash the client. 

Is there a performant solution to this?
