### ISSUE TITLE
`me.navigate` doesn't work for absolute URLs

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#403]
**Describe the bug**
`me.navigate` only works for relative paths (e.g. other pages of the Mesop app), but not absolute paths.

**To Reproduce**

```py
@me.page(path="/navigate_advanced/page1")
def page1():
  me.text("page1")
  me.button("navigate", on_click=navigate)

def navigate(e: me.ClickEvent):
  me.navigate("https://github.com/google/mesop")
```

Mesop shows an error saying that the path "https://github.com/google/mesop" does not exist.

**Expected behavior**
Mesop should navigate.

**Additional context**
The fix should be updating https://github.com/google/mesop/blob/d41a05857110a92e9bb01fb97f72a5739284978e/mesop/web/src/shell/shell.ts#L87C25-L87C33 so that it doesn't use the Angular router for absolute path navigations.

**Comment by kulkamKakarot** [comment]
i have already fixed i just want to merge the fix to main branch !
