### ISSUE TITLE
Demo Site - Boxes more responsive + Demo sidebar stays hidden after resize

### ISSUE THREAD

**Issue by richard-to** [google/mesop#407]
Now that we able to do responsive/adapative design. I think we can adjust widths so that they are more responsive. Right now they are bit too small.

Also Demo sidebar disappears when expanding

# Mobile-ish view (should take up full space here)

<img width="408" alt="Screenshot 2024-06-10 at 10 51 00 AM" src="https://github.com/google/mesop/assets/539889/80cd3241-76db-470e-a4ac-f0332c95d768">

# It's a bit hard to see what the boxes are demoing

<img width="1088" alt="Screenshot 2024-06-10 at 10 50 40 AM" src="https://github.com/google/mesop/assets/539889/a2317ac5-bc38-44ad-9981-18895ad3581e">

# Side bar not reappearing

<img width="703" alt="Screenshot 2024-06-10 at 10 51 13 AM" src="https://github.com/google/mesop/assets/539889/a6ad4bda-c6d3-4174-aaa6-1d34e2e54eb8">

**Comment by richard-to** [comment]
- Also I think we can make the sidebar a bit wider now that the sidebar can be hidden

**Comment by PasqualeCelani** [comment]
Hi, I am interested in fixing this bug in the Mesop demos page.

**Comment by richard-to** [comment]
Hi Pasquale,

Thanks for your interesting in wanting to help out with Mesop. I think you can start with the sidebar fixes first. 

The images issue I think may need a bit more discussion with @wwwillchen. I think in one of the PRs he mentioned maybe linking the images from a different source than using data URLs. We may also need to regenerate higher quality images if we make render large blocks.

**Comment by PasqualeCelani** [comment]
Thanks you very much for your response :) . I have started analyzing the bug about the sidebar and I found that it is repairing automatically in my browser (which is a safari version 17.5) when the width of the viewport is greater than 640px and is hidden if the width is less. If I understand the problem, shouldn't the sidebar not appear again when we pass from a mobile view in a desktop view?

**Comment by richard-to** [comment]
Hmm. That's interesting. I've been testing in Chrome. The behavior seems to work some times and not work other times. I've tested using dev the tools just moving the window smaller to larger. I also tested by manually adjusting my window. When I use the dev tools and select the pre-existing devices widths, that seems to work better.

**Comment by wwwillchen** [comment]
Thanks @PasqualeCelani for volunteering.

The image sizes actually aren't too bad, especially after compiling them down with webp so I think we can keep on inlining them for now. Check out the demo/readme steps: https://github.com/google/mesop/blob/main/demo/README.md#generate-screenshots for re-generating screenshots.

The demo gallery could definitely use some love, I did a hasty job of making it responsive :)

Re: the jankiness with resizing, I filed a separate issue: #420 - I don't think it's an issue with the demo gallery specifically, but with the way I implemented viewport size with window resizing, luckily I don't think the fix is too bad if you want to take a look at it.

**Comment by PasqualeCelani** [comment]
Hi @wwwillchen ,  thanks you for your  response.

I had a similar suspicion that the bug might be related to how the viewport is handled. I'll do my best to investigate and investigate the issue, since I am still learning the repo :) .

**Comment by richard-to** [comment]
I think this issue has been resolved when we updated the how the viewport media query events were firing.
