### ISSUE TITLE
Mesop can be very slow if there are a lot of child components being rendered with click event handlers

### ISSUE THREAD

**Issue by richard-to** [google/mesop#410]
I had a use case a few weeks ago where I was splitting up about 200 lines in box/text components and making them clickable. I noticed Mesop got very sluggish in this scenario so I removed it. 

Didn't look into the root cause for this yet. My hunch is tree diffing with a lot of child components. But not sure.

**Comment by wwwillchen** [comment]
Was it still slow when you removed the click handler?

**Comment by richard-to** [comment]
I haven't had a chance to dig into the root cause yet. It's likely not the click handlers. I think they were all pointing to the same click handler reference with different keys. So I think my title is slightly misleading.
