### ISSUE TITLE
Add ability to Reset Chat in mel.Chat

### ISSUE THREAD

**Issue by richard-to** [google/mesop#413]
We had a user suggest that this could be a nice feature to include in mel.chat.

We'll need to decide what feature set we want in mel.chat. We don't want to make it too full featured. So I think we can keep collecting various feature improvements to mel.chat and see what would make sense for a cohesive chat widget.

**Comment by zacharias1219** [comment]
Hey I have a good idea on how we can change this
1. on_click_reset_chat Function: This function is added to handle the "Reset Chat" button click. It clears the chat history (state.output) and the user input (state.input).

2. Reset Chat Button: A me.button component with the label "Reset Chat" is added to the chat UI. Its on_click event is bound to the on_click_reset_chat function.

3. Scrolling Improvement: The me.scroll_into_view function is used to automatically scroll to the bottom of the chat box whenever a new message is added, ensuring the latest messages are always visible.

**Comment by richard-to** [comment]
Yes, I think what you described would work.

The issue here is more on the UX / API side.

For mel.chat, we purposely kept the chat application very simple. It does the basics. The question is what should be considered basic functionality and what is functionality that would require the user to just copy the chat code and update it on their own?

At the moment, it's unclear if reset should be added in. It will likely depend on what other feature requests we get.

One way we could solve this is by allowing the user to pass in their own state object in mel.chat. This would give them more control over the internal state. So if the user passes in their own state object, then we would use that rather than the internal state object.

This would then allow the user to add a reset button somewhere to reset the state or provide other functionality to the chat widget.

**Comment by zacharias1219** [comment]
Import Optional from typing:

Added Optional to the imports to allow the custom_state parameter to be optional.
Add custom_state Parameter to chat Function:

Introduced a custom_state parameter in the chat function to allow the user to pass in their own state object.
Use custom_state if Provided:

Modified the chat function to use the provided custom_state if it is not None, otherwise fall back to using the default state.

Also is there a test file for this that I need to change.

**Comment by richard-to** [comment]
Yes, I think what you described would work. I think we can hold off on this for now until we make more decisions on the mel.chat. For now I think we will keep it as is. People will just need to create a copy of the chat widget and modify the code.

---------

If you interested in helping out on a different issue, we recently got https://github.com/google/mesop/issues/500. This is a quick change I think. So feel free to give that one a try.

**Comment by zacharias1219** [comment]
Okay will do. 
Whenever this issue is ready to be contributed to, let me know.

**Comment by richard-to** [comment]
Going to close this one for now. User will just have to fork the chat app and add the reset functionality which is fairly straightforward.
