### ISSUE TITLE
Can I write custom typescript/javascript components?

### ISSUE THREAD

**Issue by wingedrasengan927** [google/mesop#414]
Is it possible to write custom typescript/javascript components?

**Comment by wwwillchen** [comment]
Thanks for asking! We have an existing issue #95 and are working on a proposal that we'd like to share with the broader community soon to gather feedback.

**Comment by wwwillchen** [comment]
@wingedrasengan927 i've added a proposal to the linked issue #95 - please take a look and share any feedback, thanks!
