### ISSUE TITLE
Copy to Clipboard Copies $ Symbol with Command

### ISSUE THREAD

**Issue by DeepakKumarKhatri** [google/mesop#430]
**Describe the bug**
When using the "Copy to Clipboard Icon" feature on the web page, the `$`symbol (which denotes the command prompt) is also being copied along with the actual command. This causes issues when pasting the command into a terminal, as users have to manually remove the `$` symbol to execute the command.

**To Reproduce**

1. Go to https://google.github.io/mesop/getting_started/installing/
2. Click on the "Copy to Clipboard icon" next to the command.
3. Paste the copied command into a terminal.
4. `$` will also be copied there

**Expected behavior**
Only the command should be copied to the clipboard, without the `$` symbol.

**Actual Behavior**
The command, along with the `$` symbol, is copied to the clipboard.

**Example**
For instance, if the command displayed is:
`$ pip install mesop`

The copied content should be:
`pip install mesop`

However, the actual copied content is:
`$ pip install mesop`

**Impact:**
This issue requires users to manually remove the `$` symbol every time they paste the command, leading to a less smooth user experience.

**Suggested Solution:**
Modify the "Copy to Clipboard Icon" functionality to exclude the `$` symbol from the copied content.

**Desktop System Info**
- OS: Ubuntu
- Browser: Chrome

**Additional context**

**Comment by DeepakKumarKhatri** [comment]
I would love to work on this issue, please assign it to me.
Thank you!

**Comment by wwwillchen** [comment]
Hi @DeepakKumarKhatri thanks for reporting this! I noticed this too and I agree it's annoying.  We use mkdocs material for our docs site: https://squidfunk.github.io/mkdocs-material/ 

Specifically it's this feature https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code#code-copy-button which does the copy to clipboard. Maybe you could file an issue at https://github.com/squidfunk/mkdocs-material and see if you can contribute a fix there? Thanks.
