### ISSUE TITLE
plot component could render out as svg not png

### ISSUE THREAD

**Issue by ed-french** [google/mesop#433]
png as a format is relatively bulky and/or has poor zoomability/resolution

matplotlib can render charts as svg- it'd be helpful to provide that as an option and/or make it the default now all browsers support it.

For now I've just edited the library like this:
```
  figure.savefig(buf, format="svg") # was png
  data = base64.b64encode(buf.getbuffer()).decode("ascii")
  # image(src=f"data:image/png;base64,{data}", style=style)
  image(src=f"data:image/svg+xml;base64,{data}", style=style)
```

**Comment by wwwillchen** [comment]
Thanks for the suggestion! Making SVG the default sounds good to me. Would you like to send us a pull request? :)
