### ISSUE TITLE
Input component question

### ISSUE THREAD

**Issue by taupirho** [google/mesop#435]
Is it possible to have the input component only "return" what's typed into it when the user hits the enter key  rather than after every character entered

**Comment by wwwillchen** [comment]
Could you tell me a little more about your use case? You could just bind a handler to `on_enter` and not `on_input`. Is the concern around the flickering of the progress bar?

**Comment by taupirho** [comment]
No, I couldn't find an example or in your code base how to use the on_enter
event.
Lets say I have this code,

def on_enter(e: me.EnterEvent):
  state = me.state(State)


@me.page(
       path="/box",
)
def app():
    with me.box(style=me.Style(height=500, background="white",
padding=me.Padding.all(16))):
        me.input(style=me.Style(width="80%"), label="Enter image
URL",on_enter=on_enter)
        me.text('I want the string that the user has entered into the
input box here')

I want to print out the text that the user has entered in the input box
What else do I need on the on_event
function to capture what the value is in the input box

best regards,

**Comment by wwwillchen** [comment]
OK that's a good point, right now you need to use both on_input (to store the value of the input) and on_enter (to do an action). I think we could include the value of the input as part of the EnterEvent (or probably, subclass EnterEvent into `InputEnterEvent). I'll mark this as a feature request. Thanks for the feedback.

**Comment by taupirho** [comment]
Thanks Will, I did that already. Here is the full code I used. feel free to
include it in your example/demo list :-)

import mesop as me
from numba import jit
import numpy as np
import imageio
import requests
from io import BytesIO
import base64
from PIL import Image

# Numba-optimized function to convert RGB to grayscale
@jit(nopython=True)
def rgb_to_grayscale_numba(rgb):
    grayscale = np.zeros((rgb.shape[0], rgb.shape[1]), dtype=np.float64)
    for i in range(rgb.shape[0]):
        for j in range(rgb.shape[1]):
            grayscale[i, j] = (0.299 * rgb[i, j, 0] +
                               0.587 * rgb[i, j, 1] +
                               0.114 * rgb[i, j, 2])
    return grayscale.astype(np.uint8)

# Function to convert numpy array to base64
def nparray_to_base64(array):
    image = Image.fromarray(array)
    buffered = BytesIO()
    image.save(buffered, format="PNG")
    return "data:image/png;base64," +
base64.b64encode(buffered.getvalue()).decode()

# Load image from URL
#response = requests.get("
https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg
")
#img = imageio.imread(BytesIO(response.content))

# Convert to grayscale using Numba
#grayscale_img_numba = rgb_to_grayscale_numba(img)
#grayscale_img_base64 = nparray_to_base64(grayscale_img_numba)


@me.stateclass
class State:
  input: str = ""
  called_by = ""


def on_input(e: me.InputEvent):
  state = me.state(State)
  state.input = e.value


def on_enter(e: me.EnterEvent):
  state = me.state(State)
  state.called_by = 'onevent'

@me.page(
       path="/box",
)
def app():
    with me.box(style=me.Style(height=500, background="white",
padding=me.Padding.all(16))):
        s = me.state(State)
        me.input(style=me.Style(width="80%"), label="Enter image
URL",on_input=on_input,on_enter=on_enter)
        me.divider()

        if s.called_by == 'onevent':
            me.image(
                src=s.input,
                alt="Colour Image",
                style=me.Style(width="40%",padding=me.Padding.all(10))
            )

            # Load image from URL
            response = requests.get(s.input)
            img = imageio.imread(BytesIO(response.content))

            # Convert to grayscale using Numba
            grayscale_img_numba = rgb_to_grayscale_numba(img)
            grayscale_img_base64 = nparray_to_base64(grayscale_img_numba)

            me.image(
            src=grayscale_img_base64,
            alt="Grayscale Image",
            style=me.Style(width="40%",padding=me.Padding.all(10)),
            )

**Comment by aperepel** [comment]
I want to add that this is an important gap and negatively affects otherwise decent experience 

There is no clear way to debounce the input yet, and typing 3 words quickly (or rather normal speed) ends up with progress bar flashing for every typed char. I'd consider it a major flaw which needs addressing, not a feature request.

**Comment by wwwillchen** [comment]
Addressed the issues here with these PRs:

- https://github.com/google/mesop/pull/522
- https://github.com/google/mesop/pull/517
