### ISSUE TITLE
with me.button() fails as button does not return a compatible object. 

### ISSUE THREAD

**Issue by ddaugherty** [google/mesop#437]
The quick start docs show a button component being combined with a 'with' statement but the button component does not return a compatible object.

The supporting linked code example does not match the documentation as there is no 'with' combined with a button as mentioned in the QuickStart. 

Quickstart: https://github.com/google/mesop/blob/main/docs/getting_started/quickstart.md

```
with me.button(on_click=button_click):
  me.text("Increment")
```

Linked mismatched example: https://github.com/google/mesop/blob/main/mesop/examples/docs/counter.py
```
me.button("Increment", on_click=button_click)
```

**Comment by wwwillchen** [comment]
Thanks for reporting this! I've fixed it.
