### ISSUE TITLE
Class/Tailwind support on Box component

### ISSUE THREAD

**Issue by ducan-ne** [google/mesop#438]
**Is your feature request related to a problem? Please describe.**
as mentioned in #123.  As a dev has properly understood the web app. I want to reuse my web skills to mesop instead of writing raw styles.

**Describe the solution you'd like**
Support for passing classes to **Box** would be great.

**Comment by wwwillchen** [comment]
I prototyped this: https://github.com/google/mesop/pull/476, but there's a few hurdles which I've noted in the PR. I'm going to mark this as votes needed and see if more people want this before investing more into this. I know tailwind is very popular in the FE community, but it also seems quite duplicative with Mesop's [Style API](https://google.github.io/mesop/api/style/) and I think _most_ of the use cases that Tailwind does can be covered already (there's some exceptions like state selector, pseudo classes, and groups).

**Comment by richard-to** [comment]
We added a classes field to the box component, so this should allow tailwind support on the box component. Just need to specify add a tailwind generated stylesheet to the page object (for now needs to be hosted on CDN or mounted Fast API server). It seems like it should be able to extract the css classes from python files as well.
