### ISSUE TITLE
:memo: Please drop a guide to build a docker image

### ISSUE THREAD

**Issue by adriens** [google/mesop#440]
**Is your feature request related to a problem? Please describe.**

Actually, current documentation about [deployment](https://google.github.io/mesop/guides/deployment/) only shows how to run it on [Google Cloud Run](https://cloud.google.com/run) : 

> "To deploy your Mesop application, we recommend using [Google Cloud Run](https://cloud.google.com/run) because it's easy to get started and there's a [free tier](https://cloud.google.com/run#pricing). However, it's possible to deploy your Mesop to other Cloud platforms."

In my case, I need to deploy the resulting app to our local infrastructures... then we need to provide a docker Image.

**Describe the solution you'd like**

Please provide a few lines detailing how to build and run the docker image of the meseop app'. It seems like it depends on fastAPI so it should do the job (this is also what seduced me).

**Describe alternatives you've considered**

Explore and make the doc by ourselves.

**Additional context**

I'll use mesop as part of the Call for Paper for #NODES24. it will be the front-end of our ChatBOT, which strongly relies on Google APIGEE by the way

![CFP Submitted(1)](https://github.com/google/mesop/assets/5235127/249c0572-16cd-4c9b-b49b-02857027798f)

**Comment by richard-to** [comment]
Do you want the docker image to serve your custom Mesop application? I think I can provide an example of that.

-----

Just FYI, Mesop under the hood uses Flask currently.

**Comment by adriens** [comment]
Hi @richard-to , yes, that's it as for my demo I plan do deploy it as an image that was previously pushed to `ghcr.io` from our Gh ACtions... then pulled by podman.

A simple dummy code snippet or directory to acheve that would be just awesome :star_struck:

**Comment by richard-to** [comment]
Here's one of my demo apps. I added a Dockerfile to it here: https://github.com/richard-to/mesop-jeopardy/blob/main/Dockerfile

You can run this using:

```
docker-compose up -d
```

Then you can view it at `localhost:8080`

Note that the app will run, but it won't work without setting a Google API Key for Gemini.

I figure you just want an example of a Docker image, so it's not necessary.

**Comment by adriens** [comment]
Hey @richard-to , thanks a lot for your help. Yup, that's the kind of thing I was looking for.
Now, thanks to your post I have alle the required materlal to rapidly drop somehting interesting next week for my internal demo.

Thanks a lot for you help :pray: 

```dockerfile
# Build Docker image for deployment.

FROM python:3.10.14-bullseye

RUN apt-get update && \
  apt-get install -y \
  # General dependencies
  locales \
  locales-all && \
  # Clean local repository of package files since they won't be needed anymore.
  # Make sure this line is called after all apt-get update/install commands have
  # run.
  apt-get clean && \
  # Also delete the index files which we also don't need anymore.
  rm -rf /var/lib/apt/lists/*

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Create non-root user
RUN groupadd -g 900 mesop && useradd -u 900 -s /bin/bash -g mesop mesop
USER mesop

# Add app code here
COPY . /srv/mesop-jeopardy
WORKDIR /srv/mesop-jeopardy

# Run Mesop through gunicorn. Should be available at localhost:8080
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "app:me"]
```

**Comment by wwwillchen** [comment]
@richard-to would be great to add this to our deployment guide https://google.github.io/mesop/guides/deployment/ :)

I've seen quite a few questions elsewhere about this.

**Comment by adriens** [comment]
That would be awesome

**Comment by adriens** [comment]
:partying_face: Just plugged a mesop front-end  in front of our AI agent: 
![image](https://github.com/google/mesop/assets/5235127/d60873b2-50f3-4cc3-a94f-d3bbc54db821)

Behind the scene : 

- [Neo4J](https://neo4j.com/) as KnowledgeGraph
- [Quarkus](https://quarkus.io/) for REST proxy to build custom tool 
- [Podman](https://podman.io/) to run APIs
- [`Langchain4J`](https://github.com/langchain4j/langchain4j) to call llms
- `gpt4` for complex question analysis
- [Agentic](https://docs.llamaindex.ai/en/stable/examples/agent/introspective_agent_toxicity_reduction/?h=agent) : llama3 for local function calling from LLama_index function calling
- `mesop` for front-end rendering

**Comment by adriens** [comment]
[Tweet](https://x.com/rastadidi/status/1806557395864445208)

![image](https://github.com/google/mesop/assets/5235127/b56affd7-fe0c-4483-80ba-c7cf747662cd)

**Comment by richard-to** [comment]
Awesome. I'm excited that you were able to get Mesop integrated. Good luck on the presentation for #nodes24. Feel free to post the presentation if it gets accepted.
