### ISSUE TITLE
HTML Component Error: "module 'mesop' has no attribute 'html'

### ISSUE THREAD

**Issue by sonnyjon** [google/mesop#443]
**Describe the bug**
Running the sample code for the HTML component results in the error: "module 'mesop' has no attribute 'html'"

**To Reproduce**

1. Go to 'https://google.github.io/mesop/components/html/#examples.'
2. Copy code into IDE.
3. Run mesop <sample-filename.py>

**Expected behavior**
Expected to see "Custom HTML" with the link titled mesop.

**Screenshots**
![image](https://github.com/google/mesop/assets/3260654/9091a626-0c8f-4959-b2d3-b364f989bcdd)

**Desktop System Info**

- OS: Windows 11
- Browser: Microsoft Edge
- Version [126.0.2592.56 (Official build) (64-bit)]

**Additional context**
Attempted to run this simple script in PyCharm Professional's terminal window.

**Comment by richard-to** [comment]
Hi Sonnyjon,

I think the latest release 0.8.0 does not include the html module yet. I don't see it referenced: https://github.com/google/mesop/releases/tag/v0.8.0

So you'll need to wait until we cut another release.

**Comment by wwwillchen** [comment]
We've cut a new version - please upgrade to [v0.9.0](https://github.com/google/mesop/releases/tag/v0.9.0) - thanks!
