### ISSUE TITLE
Support dark theme in Mesop

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#461]
### Discussed in https://github.com/google/mesop/discussions/446

<div type='discussions-op-text'>

<sup>Originally posted by **pranshu-raj-211** June 17, 2024</sup>
I'm making a couple of websites using mesop, and I'd like to implement a dark mode toggle, cards among other stuff. Could you point me to some example in this repo where something similar has been done, so that I can make it and submit a PR?

Thanks for the wonderful work that you're doing!</div>

---

We should expose a way to use Angular Material dark theme: https://material.angular.io/guide/theming#customizing-your-colors

**Comment by adriens** [comment]
Yes, please :pray: :star_struck:

**Comment by lnarimatsu** [comment]
Interesting!
It would be nice to have an easier way to change the default color tokens for primary, secondary, etc.

**Comment by adriens** [comment]
Yes please make it happening so we can make better demos and screenshots
