### ISSUE TITLE
MIME type ('text/plain') is not executable

### ISSUE THREAD

**Issue by XinYaqiong** [google/mesop#463]
**Describe the bug**
I am following instruction to setup a demo page and run mesop locally, but the page displays loading words only. The browser console shows the error: 

**Refused to execute script from 'http://localhost:32123/zone.js/bundles/zone.umd.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.**

Just quick googling, the solution is to modify server response header, but I found no way to do that on mesop.

**To Reproduce**

1. install mesop
2. create a helloword.py (simplest one)
3. run mesop

**Expected behavior**
The page should run properly

**Screenshots**
![Uploading image.png…]()

**Desktop System Info**

- OS: windows 10
- Browser: edge and chrome
- Version edge（126.0.2592.56）/ chrome（125.0.6422.176）

**Additional context**

**Comment by wwwillchen** [comment]
Thanks for reporting this bug.

It seems similar to #441. I tried this on my windows computer and can't reproduce this issue, so I'm suspecting there may be an issue with the dependency.

Could you run the following command:

```sh
$ pip freeze > installed_modules.txt
```

This will list all your installed Python and save it into a text file. And then please share the text file. Thanks.

In the meantime, you can try using Mesop on Colab: https://colab.research.google.com/github/google/mesop/blob/main/notebooks/mesop_colab_getting_started.ipynb

**Comment by wwwillchen** [comment]
Also, just checking how are you installing Mesop? If you're not using a virtual environment, please follow these steps: https://google.github.io/mesop/getting_started/installing/#create-a-venv-environment

**Comment by wwwillchen** [comment]
I believe this is fixed - see: https://github.com/google/mesop/issues/441#issuecomment-2188207000
