### ISSUE TITLE
The scrollIntoView command scrolls using the outer frame window scroll bar rather than the nearest scrollbar inside the frame

### ISSUE THREAD

**Issue by richard-to** [google/mesop#471]
- The issue can be seen here: https://google.github.io/mesop/components/chat/#overview
- Send a few chat messages
- The window outside the frame will scroll rather than the scrollbar of the chat div which is what we'd want here

Maybe the solution is here: https://stackoverflow.com/a/67433987/177646

So update this: https://github.com/google/mesop/blob/2a2526ac570808a209c7c7f38350b8d713307d3b/mesop/web/src/shell/shell.ts#L114?

But not sure though. 

Docs seem to say it should use the "scrollable ancestor" -> https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

**Comment by KamronP23** [comment]
I can work on this issue

**Comment by richard-to** [comment]
Sure. Sounds good.

**Comment by KamronP23** [comment]
I found that the scroll in the chat box works when the mouse is hovering over the chat box. When the mouse is outside of the chat box then the browser scrolls. Going to test the scrolling behavior a bit further by creating an example demo.

**Comment by KamronP23** [comment]
Upon further testing, and running the demo app, the scrolling feature in the chat seems to work, whichever component the mouse is hovering will scroll

**Comment by richard-to** [comment]
That's good to know, Kamron. Thanks for looking into the bug. I'll close it then as not reproducible.
