### ISSUE TITLE
Did the docs move?

### ISSUE THREAD

**Issue by mneedham** [google/mesop#479]
When I go to https://google.github.io/mesop/

<img width="666" alt="2024-06-19_16-24-16" src="https://github.com/google/mesop/assets/13220/cad4fa54-9458-47ff-bedc-8320c1eb8abc">

**Comment by richard-to** [comment]
It should be still in the same location. The link you posted worked for me. It may have been a temporary issue. Can you give it a another try?

**Comment by richard-to** [comment]
I'm going to close this issue. I checked using some "Is this site down?" checkers and it seems ok with those. Feel free to reopen if it's not working for you still.

**Comment by mneedham** [comment]
Works for me now. Weird - dunno why it wasn't working before. I tried on my computer and phone and got the same issue
