### ISSUE TITLE
local vs. deployed: mesop locally is gracious about RadioOptions under Select

### ISSUE THREAD

**Issue by ghchinoy** [google/mesop#499]
**Describe the bug**
I had the code iterating over text to create options under a `me.select()` and I inadvertently used `me.RadioOption` - when running mesop locally, it worked - i.e. the RadioOption was rendered properly as a SelectOption.
When I deployed this to Cloud Run though, I received the error   
```Input should be a dictionary or an instance of SelectOption [type=dataclass_type, input_value=RadioOption(label='Increa...crease brand awareness'), input_type=RadioOption];
```

**To Reproduce**

1. create a `me.select()` and purposefully put a `me.RadioOption()` or two underneath it
2. run locally with `mesop` and see that these appear to be select options
3. deploy and get an error

**Expected behavior**

local `mesop` should throw an error and not allow Radio options under a Select

**Screenshots**

**Desktop System Info**

**Additional context**

**Comment by wwwillchen** [comment]
Thanks for filing this as well - I think this is very similar to the issue in https://github.com/google/mesop/issues/498#issuecomment-2187485666 where you're using Pydantic v1 locally which is not as strict as Pydantic v2.

FWIW, I find it very surprising that Pydantic v1 allows `me.RadioOption` in lieu of `me.SelectOption`. Similar to the other issue, I'd like to wait for feedback from other people as I suspect this is a fairly rare issue for most of our users.
