### ISSUE TITLE
Add more border style options

### ISSUE THREAD

**Issue by seekerquest** [google/mesop#500]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The `me.borderside` style property has only 'none' and 'solid' as options. Would be nice to expand options to 'dashed', 'dotted', 'double', etc....

**Comment by richard-to** [comment]
I think the only change needed is updating this line (plus the comment): https://github.com/google/mesop/blob/main/mesop/component_helpers/style.py#L81

**Comment by seekerquest** [comment]
Thank you for highlighting that @richard-to. i think i can pick this one up.

**Comment by zacharias1219** [comment]
Hey I change the file to have this code
style: (
    Literal[
      "none",
      "solid",
      "dashed",
      "dotted",
      "double",
      "groove",
      "ridge",
      "inset",
      "outset",
      "hidden",
    ]
    | None
  ) = None
