### ISSUE TITLE
Request for Single Root and Graph component.

### ISSUE THREAD

**Issue by mattjoyce** [google/mesop#511]
Provide a component which can be used to display hierarchical data.
Either a tree structure, similar to a common folder structure, where the containers can contain objects or container.

Or a Graph with Nodes and Edges, perhaps based on Cytoscape.

**Describe alternatives you've considered**
Embed Cytoscape.js in an iframe?

**Comment by wwwillchen** [comment]
I'd recommend using [web component](https://google.github.io/mesop/web_components/) to wrap cytoscape. Feel free to re-open this if you run into an issue.
