### ISSUE TITLE
Katex formula rendering in chat bubbles

### ISSUE THREAD

**Issue by HarleyCoops** [google/mesop#519]
**Is your feature request related to a problem? Please describe.**
I use a lot of formulas in chat output and they all render in text. 

**Describe the solution you'd like**
There must be a way to call a katex component and have that render in the bubble, just cant get it to work. 

**Describe alternatives you've considered**
Only katex so far 

**Additional context**

**Comment by wwwillchen** [comment]
I'd recommend copying the chat component: https://github.com/google/mesop/blob/main/mesop/labs/chat.py and using a [web component](https://google.github.io/mesop/web_components/) to wrap katex.

Feel free to re-open this if you run into an issue.

**Comment by HarleyCoops** [comment]
That’s exactly what I’m doing but katex isn’t working in mesop. Thats why I raised the ticket. On Jun 24, 2024, at 11:52 PM, Will Chen ***@***.***> wrote:﻿
I'd recommend copying the chat component: https://github.com/google/mesop/blob/main/mesop/labs/chat.py and using a web component to wrap katex.
Feel free to re-open this if you run into an issue.
