### ISSUE TITLE
html css

### ISSUE THREAD

**Issue by maxmurugan** [google/mesop#528]
import mesop as me

@me.page(path="/html_demo")
def app():  
    me.html("""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                p {
                    color: blue;
                    font-size: 20px;
                }
                table {
                    width: 100%;
                    border-collapse: collapse;
                }
                table, th, td {
                    border: 1px solid black;
                }
                th, td {
                    padding: 8px;
                    text-align: left;
                }
                th {
                    background-color: #f2f2f2;
                }
            </style>
        </head>
        <body>
            <p>I'm a big, blue, <strong>strong</strong> paragraph</p>
            <table>
                <tr><th>First_Name</th><th>Last_Name</th><th>Marks</th></tr>
                <tr><td>Sonoo</td><td>MURUGAN</td><td>38</td></tr>
                <tr><td>James</td><td>William</td><td>80</td></tr>
                <tr><td>Swati</td><td>Sironi</td><td>82</td></tr>
                <tr><td>Chetna</td><td>Singh</td><td>72</td></tr>
            </table>
        </body>
        </html>
        """
    )
    
    
   css not working this method ,how to use css in mesop?

**Comment by maxmurugan** [comment]
import mesop as me

@me.page(path="/html_demo")
def app():  
    me.html("""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                p {
                    color: blue;
                    font-size: 20px;
                }
                table {
                    width: 100%;
                    border-collapse: collapse;
                }
                table, th, td {
                    border: 1px solid black;
                }
                th, td {
                    padding: 8px;
                    text-align: left;
                }
                th {
                    background-color: #f2f2f2;
                }
            </style>
        </head>
        <body>
            <p>I'm a big, blue, <strong>strong</strong> paragraph</p>
            <table>
                <tr><th>First_Name</th><th>Last_Name</th><th>Marks</th></tr>
                <tr><td>Sonoo</td><td>MURUGAN</td><td>38</td></tr>
                <tr><td>James</td><td>William</td><td>80</td></tr>
                <tr><td>Swati</td><td>Sironi</td><td>82</td></tr>
                <tr><td>Chetna</td><td>Singh</td><td>72</td></tr>
            </table>
        </body>
        </html>
        """
    )

**Comment by wwwillchen** [comment]
Looks like Angular's [DomSanitizer](https://angular.dev/api/platform-browser/DomSanitizer?tab=description) is removing the <style> tag.

Try using https://google.github.io/mesop/web_components/. If you use Lit to create a web component, you can use their style API to accomplish something similar to your example: https://lit.dev/docs/components/styles/

If you have trouble using web components, feel free to re-open this issue.
