### ISSUE TITLE
Provide support for SVG xml in icon

### ISSUE THREAD

**Issue by ghchinoy** [google/mesop#529]
**Is your feature request related to a problem? Please describe.**
It would be great to support custom svg xml as an input for the icon component

**Describe the solution you'd like**
extend icon to allow in-lining (or file path input reference) for svg xml

https://material.angular.io/components/icon/overview#svg-icons

**Describe alternatives you've considered**
Haven't tried any other way to add svg to mesop

**Comment by wwwillchen** [comment]
Thanks for filing an issue. Agree, it would be nice to eventually support this. For now, you should be able to use web components to inline SVGs: https://google.github.io/mesop/web_components/ - let me know if you run into troubles doing that.

**Comment by ghchinoy** [comment]
Works like a charm, thank you!

**Comment by ghchinoy** [comment]
As an update, I created a stand alone component for this https://github.com/ghchinoy/mesop-svg-icon
