### ISSUE TITLE
Disable hot reload!

### ISSUE THREAD

**Issue by Saya47** [google/mesop#551]
Hello! I would like a CLI argument that would disable the hot reload feature.
Why, you may ask? Because I run 2 mesop instances:

- One on port 32123 which is going to run an inference requests that will take around an hour to complete, so I want the second web app to not keep restarting while I'm editing and updating my codes!
- Another one on port 32124, which I will be using hot reload with, which I will update my code files and see changes happening live!

I thought about this, and since the first one runs first and generates the `.pyc` files and loads all code in memory, there won't be an issue if the code files update with the second web app and the first one can work correctly I presume.
https://stackoverflow.com/questions/15839555/when-are-pyc-files-refreshed

**Comment by richard-to** [comment]
As a temporary workaround, I wonder if you can use the --prod flag? I think with that flag enabled, hot reloading is disabled.

**Comment by Saya47** [comment]
Yes! That works! Thanks very much!

**Comment by richard-to** [comment]
Seems like using --prod was good enough. So I'm going to close this issue for now.
