### ISSUE TITLE
Add the ability add custom assets to a static folder

### ISSUE THREAD

**Issue by richard-to** [google/mesop#564]
This may help for features such as:

- Adding custom style sheets (without needing a CDN or external source)
- Adding favicon (would need a parameter to specify the URL)
- Static images such as logos and application assets (mainly useful development purposes and for people who don't want to optimize with CDNs and external hosting)
- Static folder should probably be per page or should this be more a of global option that allows different static folders to be exposed?

**Comment by richard-to** [comment]
Custom assets can be added by mounting FastAPI. See: https://github.com/google/mesop/issues/803

I don't think it solves the favicon issue yet since we don't have an API to set a favicon.

**Comment by wookayin** [comment]
Came across from Googling: it's not very clear how static assets can be served. Attaching 'me' to another wsgi app (fastapi) #803 doesn't seem a good enough solution (e.g. #894).
