### ISSUE TITLE
Uploader Component Parameters - Style (and others)

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#568]
### Discussed in https://github.com/google/mesop/discussions/559

<div type='discussions-op-text'>

<sup>Originally posted by **lnarimatsu** June 28, 2024</sup>
“Could the Uploader Button be enhanced by adding a **style parameter**? This would allow us to customize its appearance. 

Additionally, could we consider incorporating all parameters that are currently available in the button component? This would provide greater flexibility and consistency across our components.

_Func Uploder_
![image](https://github.com/google/mesop/assets/11890782/68823a87-2557-4045-91f3-ed328695ad28)

_Func Button_
![image](https://github.com/google/mesop/assets/11890782/58e1e74b-efae-4714-b20e-6a2598464368)
</div>

---

@richard-to any thoughts?

**Comment by richard-to** [comment]
Yeah I think that's a good idea, especially being able to style the button properly. I think the main thing we can leave off is on click. Should be fairly straightforward.
