### ISSUE TITLE
Select example not rendering in components doc

### ISSUE THREAD

**Issue by ghchinoy** [google/mesop#596]
**Describe the bug**

https://google.github.io/mesop/components/select/

**To Reproduce**

1. Go to [Components Select page in docs](https://google.github.io/mesop/components/select/)
2.. See error

**Expected behavior**

**Screenshots**

![image](https://github.com/google/mesop/assets/469685/9b160b26-01dc-4a47-b86f-3ab75be9f6b2)

**Desktop System Info**

**Additional context**

**Comment by richard-to** [comment]
Good catch. Looks like url should be: https://google.github.io/mesop/demo/?demo=select_demo

**Comment by richard-to** [comment]
Should be fixed now.
