### ISSUE TITLE
Adding a Authenticator demo in the demo use cases section 

### ISSUE THREAD

**Issue by itsBaivab** [google/mesop#608]
**Is your feature request related to a problem? Please describe.**
A saw that there is no demo related to how authentication works in mesop. 

**Describe the solution you'd like**
It is better to have a username, password filed and a login button that will welcome a user after logging. If the password and username fields are empty then it will through an error to the user. 

**Additional context**

this is how it should look like 
![image](https://github.com/user-attachments/assets/a6ac86ec-802d-4675-a820-2ac30799b9b2)

can i send a pr?

**Comment by wwwillchen** [comment]
Feel free to send a PR - here's our contributing guide:  https://google.github.io/mesop/internal/contributing/

**Comment by itsBaivab** [comment]
Submitted a pr let me know if I need to perform any changes.
