### ISSUE TITLE
Focus input field of mesop.labs.Chat after hitting enter

### ISSUE THREAD

**Issue by FlorianWilk** [google/mesop#609]
**Is your feature request related to a problem? Please describe.**
When using the mesop.labs.Chat component in a frontend, i always have to re-focus the input text field, after submitting a message. 

**Describe the solution you'd like**
Focussing the InputTextField after submitting a message in mesop.labs.Chat

**Comment by rsenjins** [comment]
In addition to that, it would be great if it is possible to add autofocus to a component on loading of a page. So if loading a page it automatically focusses on the input component for instance.

**Comment by richard-to** [comment]
I think adding focus should be doable by creating a "command" similar to what we do with scroll_into_view command: https://github.com/google/mesop/pull/315

I think it should also be possible to use this approach to focus on loading use the load hook (I'd have to verify that commands can be executed on the load event, but seems likely).
