### ISSUE TITLE
Adding a Search box demo

### ISSUE THREAD

**Issue by itsBaivab** [google/mesop#610]
**Is your feature request related to a problem? Please describe. **
I saw there is no demo for a search box. It's great to have one for easy intermigration. 

**Describe the solution you'd like**
The search field should be able to search from multiple results. It should be able to dynamically change its results on the basis of current text in the search field.

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/user-attachments/assets/8e88fc19-961b-4f25-8e8a-caa3fbb874bb)

**Comment by richard-to** [comment]
I think for a search box, we could try adding the Angular Autocomplete component (https://material.angular.io/components/autocomplete/overview). I haven't tested if this component would be easy to add to Mesop or not.

So I think if we were to add search box demo, we'd try to make it look similar to the Angular Autocomplete component.

I do agree that this is a good use case to cover. Thanks for the suggestion.

**Comment by itsBaivab** [comment]
Sure, I will try to make a pr on it.

**Comment by richard-to** [comment]
Going to close this issue since we'll likely be adding the Angular Autocomplete component.
