### ISSUE TITLE
Create a Performance guide

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#618]
@richard-to I think we need some kind of guide. Technically all the information is in https://google.github.io/mesop/api/config/ but it's not obvious to look there. I think having some kind of "Performance" guide would be very helpful.

Something like:

- How do I diagnose my performance problem? e.g. is it because state is too large or some other reason
- If state is a problem, how do I pick which state session backend is suitable?

**Comment by richard-to** [comment]
Yeah, I agree. I think it would definitely be helpful. Definitely the info in config is a bit messy and unorganized. I think the main thing is to be able to distill the information in a way that is clear and concise.

And in terms of the state session backends, I do feel that we need to do some more loading testing on the various options to see how they actually fare.
