### ISSUE TITLE
Add Tab Component

### ISSUE THREAD

**Issue by seekerquest** [google/mesop#648]
**Is your feature request related to a problem? Please describe.**
Add a Tab component as described in [https://material.angular.io/components/tabs/overview](https://material.angular.io/components/tabs/overview)

**Describe the solution you'd like**
A potential implementation could be something like this:

```python
import mesop as me

with me.tabs():
      with me.tab('tools'):
            me.text('Tools Section')
```

But more broadly speaking, is there a comprehensive way for the community to add more components to enrich the framework ? maybe a well documented process could help!

**Comment by wwwillchen** [comment]
Hi @seekerquest - we have an existing issue at #93 so I'm going to dedupe this issue, but you're more than welcome to work on #93.

Take a look at our [contribution guide](https://google.github.io/mesop/internal/contributing/#contributing-code) and follow our dev environment docs.

We have a doc page for adding a new component:
https://google.github.io/mesop/internal/new_component/

Feel free to reference https://github.com/google/mesop/pull/640 which is a PR I recently did to add a new component.
