### ISSUE TITLE
Allow Default Value in Dropdown Lists

### ISSUE THREAD

**Issue by linderjo** [google/mesop#682]
Hi, 

I would like to suggest/request an additional feature for the Select or SelectOption Component. 

Additional Feature:
It is not possible to select a dropbox item by default when the page is loaded. 
It is possible to preset the value when the page is loaded but the dropdown box is not able to represent this value as no default value can be set. 

Suggested Solution:
Implement an additional option for the Select or SelectOption component to set a default selection when the page is loaded. 
Suggestion 1: For the select component an additional option could be added with Id or label of the default SelectOption.
Suggestion 2: Add a bool option to SelectOption component to set true if it is selected by default. 

Current (ugly) workaround:
Preset the value when the page is loaded. Set the value as label of the Dropdown component to display the "fake" selected item. When another option is selected the label is updated to the actual name of the Dropdown List.

Many thanks!

**Comment by richard-to** [comment]
Are you talking about Select component (https://google.github.io/mesop/components/select)? 

I think you can set the starting value of the Select component using the `value` field. However there is a bug when multiple=True. Then setting the default value does not work (it also wouldn't allow for multiple defaults). See https://github.com/google/mesop/issues/681


-----

Here's an example:

```python
import mesop as me


@me.stateclass
class State:
  selected_values: list[str]


def on_selection_change(e: me.SelectSelectionChangeEvent):
  s = me.state(State)
  s.selected_values = e.values


@me.page(
  security_policy=me.SecurityPolicy(
    allowed_iframe_parents=["https://google.github.io"]
  ),
  path="/select_demo",
)
def app():
  me.text(text="Select")
  me.select(
    label="Select",
    value="value3",  # Set default to value3
    options=[
      me.SelectOption(label="label 1", value="value1"),
      me.SelectOption(label="label 2", value="value2"),
      me.SelectOption(label="label 3", value="value3"),
    ],
    on_selection_change=on_selection_change,
    style=me.Style(width=500),
    multiple=False,
  )
  s = me.state(State)
  me.text(text="Selected values: " + ", ".join(s.selected_values))
```

**Comment by linderjo** [comment]
Hi Richard, 
Thanks for your quick response !
I tried to do it this way but had a typo in the value name. Therefore I thought I does not work this way.

Thanks for this great framework !

Regards
Jonathan
