### ISSUE TITLE
Not able to set`flex-shrink=0`

### ISSUE THREAD

**Issue by richard-to** [google/mesop#69]
When I try to set `flex-shrink=0`, it's not showing up in the generated CSS. I believe this is because 0 would be the same as undefined/null/etc in the current code. 

As a quick test, I was able to make a small change that worked (EDIT: Actually that does not work since the type is number, so the default I guess would be 0 -- I'm not too familiar with typescript):

```
  if (styleObj.getFlexShrink() || styleObj.getFlexShrink() === 0) {
    style += `flex-shrink: ${styleObj.getFlexShrink()};`;
  }
```

One reason for this issue is that that flex-shrink defaults to 1 (See https://developer.mozilla.org/en-US/docs/Web/CSS/flex-shrink).

So it by not including the style, I'm not able to get the flex-shrink = 0 behavior that I was looking for.

This may be an issue with other styles. We may want to explicitly check for null/undefined for all styles. So if it is set, then we should use the value that is specified.

Source location: https://github.com/google/mesop/blob/24f77303b6b5f014ae882e74d35464b06a76632d/mesop/web/src/utils/styles.ts#L5

**Comment by richard-to** [comment]
Since proto3 doesn't allow us to set default values, maybe one option is to set a default of 1 in https://github.com/google/mesop/blob/main/mesop/component_helpers/style.py#L199

Then we can update the condition to check for if it equals 1 for flex shrink in https://github.com/google/mesop/blob/main/mesop/web/src/utils/styles.ts#L70

-------

Alternatively we could also change the proto data type from int to string. That way an empty string could act as a not set and then default to whatever is the default for that style. Downside is we'd lose the type checking of int values. And would probably need some input validation at some point.

I see some cases where you have the possibility of int | str in style.py and the corresponding proto value is a str. So that could work here and keep things consistent with existing behavior.

-------

**Comment by wwwillchen** [comment]
Using a str proto value SGTM - thanks for investigating into this. I didn't know flex-shrink had a default value of 1 😂
