### ISSUE TITLE
doc: embedded example 404'ing

### ISSUE THREAD

**Issue by ghchinoy** [google/mesop#695]
**Describe the bug**

https://mesop-tdcukehw6q-uc.a.run.app/embed/chat_inputs is 404'ing and is referenced on the following pages

* https://google.github.io/mesop/
* https://google.github.io/mesop/components/input/

**To Reproduce**

1. Go to https://google.github.io/mesop/
See 
![image](https://github.com/user-attachments/assets/9ecc09a0-476e-40aa-9654-94f369739e21)

**Expected behavior**

Example of components rendered

**Screenshots**

**Additional context**

**Comment by wwwillchen** [comment]
We've fixed the demo gallery, including the embedded demos. 

BTW, we've switched from Cloud Run to Hugging Face spaces so the URL is now: https://wwwillchen-mesop.hf.space/
