### ISSUE TITLE
Firebase Auth "redirect" broken

### ISSUE THREAD

**Issue by tpcgold** [google/mesop#713]
**Describe the bug**
The Firebase auth example is broken due to the Cross origin redirect login change in chrome. 
![image](https://github.com/user-attachments/assets/7516eb95-c3fb-41ae-8efe-d5f952b51b42)

**To Reproduce**
Run the example in this repo and it will not work if the app is hosted on different domains than firebase.

**Expected behavior**
Redirect flow should work again. 

**Workaround**
"popup" flow is a workaround but one cannot auto-login with the popup flow

One potential solution would be to implement a transparent proxy within mesop:
[https://firebase.google.com/docs/auth/web/redirect-best-practices?hl=en&authuser=0#proxy-requests](https://firebase.google.com/docs/auth/web/redirect-best-practices?hl=en&authuser=0#proxy-requests)
so request to `/__/auth/` can be forwarded. 
or mesop allows to serve local html and js files directly under a path.

**Comment by tpcgold** [comment]
i've created a workaround for mesop with popup here:
```javascript
import {html, LitElement} from 'https://cdn.jsdelivr.net/gh/lit/dist@3/core/lit-core.min.js';
import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js';
import {
    getAuth,
    OAuthProvider,
    onAuthStateChanged,
    signInWithPopup,
    signOut
} from 'https://www.gstatic.com/firebasejs/10.12.4/firebase-auth.js';

const firebaseConfig = {
    apiKey: '',
    authDomain: '',
    projectId: '',
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const provider = new OAuthProvider('');

class FirebaseAuthComponent extends LitElement {
    static properties = {
        isSignedIn: {type: Boolean},
        authChanged: {type: String},
    };

    constructor() {
        super();
        this.isSignedIn = false;
    }

    createRenderRoot() {
        return this;
    }

    firstUpdated() {
        this.checkAuthState();
    }

    checkAuthState() {
        onAuthStateChanged(auth, user => {
            this.isSignedIn = !!user;
            const token = user ? user.getIdToken() : Promise.resolve('');
            token.then(token => this.dispatchEvent(new MesopEvent(this.authChanged, token)));
            if (!user) this.signInWithPopup();
        });
    }

    signInWithPopup() {
        signInWithPopup(auth, provider).then(result => {
            this.isSignedIn = true;
            result.user.getIdToken().then(token => this.dispatchEvent(new MesopEvent(this.authChanged, token)));
        }).catch(console.error);
    }

    signOut() {
        signOut(auth).then(() => {
            this.isSignedIn = false;
            this.dispatchEvent(new MesopEvent(this.authChanged, ''));
        });
    }

    render() {
        return html`
            <div id="firebaseui-auth-container" style="${this.isSignedIn ? 'display: none' : ''}"></div>
            <div class="firebaseui-container" style="${this.isSignedIn ? '' : 'display: none'}">
                <button @click="${this.signOut}">Sign out</button>
            </div>
        `;
    }
}

customElements.define('firebase-auth-component', FirebaseAuthComponent);
```

this is working with the limitation that the popup-blocker needs to be whitelisted for the domain mesop is running

**Comment by richard-to** [comment]
Thanks for pointing out this use case.

Yes, the pop up option does seem less than ideal.

I do think the nginx proxy described in the docs seems like the easiest approach. However, I'm not as familiar with other options (outside of nginx) in terms of what people would need to do.

Yes, I think, if we do https://github.com/google/mesop/issues/564, that could allow people to do option 4.

In terms of your pop up implementation, it could be good to have your example in the repository as an example.

**Comment by richard-to** [comment]
I see. Yes, I think it would make sense if we can forward the request headers somehow. That seems like useful functionality. Under the hood we use Flask, so we should be able to get the headers and make them accessible in Mesop.

I think maybe just need to determine how the API should look. Add them to the LoadEvent is definitely one possible as you suggest. I'm wondering if there could be any other use cases outside the load event where it may be useful.

**Comment by wwwillchen** [comment]
@tpcgold we just added support in https://github.com/google/mesop/releases/tag/v0.12.3 for mounting other web servers with Mesop, which means you could use a web framework like FastAPI or Flask and use that to proxy the  request to `/__/auth/` - I'll close this for now, but feel free to re-open if you're still running into issues.
