### ISSUE TITLE
Web component properties do not seem to accept objects or arrays

### ISSUE THREAD

**Issue by richard-to** [google/mesop#730]
Example:

```
  static properties = {
    value1: {type: Object},
    value2: {type: Array},
  };
```

I'm not sure if I'm doing something wrong here, but when I try to pass in an Array or Object, I get undefined.

**Comment by wwwillchen** [comment]
I think I made a bug here: https://github.com/google/mesop/blob/1fb6c0710a6f0db62ee8197f72b629a3b0e82905/mesop/web/src/component_renderer/component_renderer.ts#L213C23-L213C35

Will try to fix this soon
