### ISSUE TITLE
Add `table` component

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#75]
- https://material.angular.io/components/table/overview
- In particular, Python developers oftentimes want to display a dataframe as a table UI

**Comment by richard-to** [comment]
I'd like to try taking on this issue. I think it'd be a good way for me to get a better understanding of the codebase.

**Comment by wwwillchen** [comment]
Fantastic! I think this will be very useful - this was requested by an internal user and I would also like to use this as well :)

A couple of ideas around the API, but please come up with your own ideas!

- I'd consider having a simple API, e.g. `me.table(df)` where df is a Pandas dataframe. This is a very common use case. As prior art, take a look at what [Streamlit has done](https://docs.streamlit.io/library/api-reference/data/) with its dataframe and table components.
- As a follow-up feature, it may be nice (I have a personal use case :)) to provide some kind of `on_row_click` API so users can do custom interactivity (e.g. navigate to a page). There's a lot of potential interactivities (e.g. pagination, column sorting, filtering, etc), so feel free to be iterative about this and implement something simple (e.g. a static table) to begin with.

In case you haven't seen it, take a look at the docs for creating a new component: https://google.github.io/mesop/internal/new_component/#potential-exploration-areas

In particular, the scaffold_component.sh script is quite helpful.

**Comment by richard-to** [comment]
I definitely agree about starting off simple first. Definitely agree that there's a lot of functionality that can be added. The Streamlit stuff is very cool.

**Comment by wwwillchen** [comment]
Basic table component done in above PR - we can open more issues based on user feedback.
