### ISSUE TITLE
Multiline input

### ISSUE THREAD

**Issue by tpcgold** [google/mesop#763]
**Is your feature request related to a problem? Please describe.**
Currently, every input is just a single line. We would like to have a parameter for the input component to allow multiline inputs (visible correctly formatted and if needed with a scrollbar)

This feature is vital if one is pasting complex text and wants to edit it in the input field or if one is pasting code (e.g. usage like copilot chat) into the input field.

One slightly bug we discovered with the input component here as well: the shift + enter is recognized as if just enter is pressed. (currently, as multi-line is not supported, nothing should happen)

**Describe the solution you'd like**
Parameter on the input component

**Describe alternatives you've considered**
Custom component for the input -> not optimal as it should be native to MESOP

**Comment by wwwillchen** [comment]
Check out textarea, which is a multi-line text input component: https://google.github.io/mesop/components/textarea/

If you need a multiline text input with custom keyboard shortcuts, then your best bet is using web components: https://google.github.io/mesop/web-components/ which is more work but gives you the most flexibility.
