### ISSUE TITLE
Support functools.partial instances as event handlers

### ISSUE THREAD

**Issue by malmaud** [google/mesop#766]
Currently you cannot pass an instance of functools.partial as an event handler since several places in helper.py assume the handler has a `__call__` and `__module__` property and can be passed to `inspect.getsource` (in `compute_fn_id` and `wrap_hander_with_event`). 

But you *can* pass a lambda, which is conceptually similar.

If this can't be supported for whatever reason, then maybe the event handler type hints should be changed since event handlers are annotated as `Callable` and a `partial` is a `Callable`.

**Comment by wwwillchen** [comment]
Thanks for filing this issue. @malmaud could you take a look at this pull request? https://github.com/google/mesop/pull/789

I'm not super familiar with functools.partial, and in particular how to calculate a stable id (which is essentially what `compute_fn_id` does) that is sent back and forth between the client and server so we know which callback/function to call when an event is triggered.

**Comment by malmaud** [comment]
Thanks for the PR - I commented there that this looks like a reasonable solution, but I'm not enough of an expert in the `partial` implementation to spot if there were subtle mistakes
