### ISSUE TITLE
Mesop Guide Async seems to be broken

### ISSUE THREAD

**Issue by WernerJacoby** [google/mesop#773]
**Describe the bug**
copied and run example code 'Mesop Guide Async'
(as given here: https://google.github.io/mesop/guides/interactivity/#Async)

**To Reproduce**

1. run app: Mesop async.py
2. Click on button 'async'
4. See error "'async_generator' object is not iterable'

**Expected behavior**
fetch two asynchronous inputs

**Screenshots**
see appendix

**Desktop System Info**

- OS: macOS 14.5 (23F79)
- Browser safari
- Version 17.5

[Mesop-async_await.pdf](https://github.com/user-attachments/files/16568904/Mesop-async_await.pdf)

**Comment by wwwillchen** [comment]
Sorry about that - the async feature was just made and we haven't published a new version of Mesop yet - I'll do it next week and then close this issue. Thanks

**Comment by wwwillchen** [comment]
We've just cut a new release https://github.com/google/mesop/releases/tag/v0.12.0 which includes async support. Please check it out - thanks for waiting!
