### ISSUE TITLE
uploader_app.py throws TypeError: UploadedFile.__init__() missing 1 required positional argument: 'contents'

### ISSUE THREAD

**Issue by prakashvra** [google/mesop#774]
**Describe the bug**
While trying to launch the uploader sample app, throws an initialisation error

TypeError: UploadedFile.__init__() missing 1 required positional argument: 'contents'

**To Reproduce**

In my local, I have modified the page path to "/uploader"

1. Run mesop uploader_app.py
2. Navigate to  http://localhost:32123/uploader
3. See error in the terminal 
TypeError: UploadedFile.__init__() missing 1 required positional argument: 'contents'

**Expected behavior**
Expect to see the page with 'Upload Image' button 

**Screenshots**

**Desktop System Info**

- OS: Windows 10
- Browser - chrome
- Version 127

**Additional context**
I was able to fix the issue by adding init function to the class State

@me.stateclass
class State:
  file: me.UploadedFile

  def __init__(self):
    self.file = me.UploadedFile(b"", name="", size=0, mime_type="")

**Comment by wwwillchen** [comment]
Try upgrading mesop:

```py
pip install -U mesop
```

In Mesop [v0.10.0](https://github.com/google/mesop/releases/tag/v0.10.0) we updated UploadedFile which should fix this state serialization issue. Thanks.
