### ISSUE TITLE
The `columns` property should be string instead of int.

### ISSUE THREAD

**Issue by richard-to** [google/mesop#79]
When I was looking at the `columns` property in https://developer.mozilla.org/en-US/docs/Web/CSS/columns, it seems that it allows more than integers.

Is there a reason only integers are allowed? Otherwise seems fairly straightforward to just convert the `columns` property to a string.

**Comment by wwwillchen** [comment]
Good point, I was thinking of only the simplest cases, but you're right there's a lot more options. I would recommend doing a union, i.e. `int | str`. This is what we do for other CSS properties (e.g. for sizes, we do `int | str` and int is automatically treated as pixels).

Another benefit of union is to preserve backwards compatibility, although TBH, there isn't that much usage of Mesop so this isn't a huge consideration at the moment, but it's nice to preserve it when posssible.
