### ISSUE TITLE
Support mounting Mesop with other Python servers

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#803]
# Motivation

This could satisfy a few advanced use cases:

- Allows client-side code (web components) to directly call long-running APIs which could support: 1) not blocking state updates and 2) cancelling an LLM call (see #623)
- Support serving custom files (e.g. download links #453)
- Allow forwarding requests which can be needed in certain auth integrations (see: #713)

# Considerations

- We'd like to eventually migrate from Flask to an async-friendly framework like Quart or Starlette so we shouldn't directly expose the framework so we have flexibility to do this migration. However, we should try to provide an API that's similar so the learning curve is reasonably small.

# API proposal

## Simple request

```py
@me.route(methods=["GET", "POST"], path="/foo")
def route():
  return output
```

## Async

```py
@me.route(path="/books/{book_id}")
async def route(book_id: int):
  output = await call_api()
  return output
```

## Path parameters

```py
@me.route(methods=["GET", "POST"], path="/books/{book_id}")
def route(book_id: int):
  return output
```

## Query params
```py
@me.route(methods=["GET", "POST"], path="/books")
def route():
  qp = me.query_params()
  return do_work(qp["foo"])
```

output could be:

- dict
- json
- binary file

# Questions

- Should we try to expose Fast API directly? Or, should we implement this ourselves?
- Should we allow path-dependent ordering? See [FastAPI](https://fastapi.tiangolo.com/tutorial/path-params/#order-matters)
- Should we support multiple HTTP verbs in a single HTTP handler?
- Should you be able to access `me.state(State)`? It would be nice to do this, otherwise it creates an island but you could update the state indirectly from the client-side code.
- https://fastapi.tiangolo.com/tutorial/body/#request-body-path-query-parameters:~:text=The%20function%20parameters%20will%20be%20recognized%20as%20follows%3A

**Comment by wwwillchen** [comment]
Perhaps we can just offer a way to mount apps, e.g.:

```py
# app is any WSGI app
me.mount_app(app)
```

https://flask.palletsprojects.com/en/2.3.x/patterns/appdispatch/
https://github.com/django/asgiref/tree/main

**Comment by wwwillchen** [comment]
Turns out you can actually mount Mesop because `me` actually satisfies the WSGI protocol. Here's an example of combining a Mesop app and a FastAPI app together:
https://github.com/wwwillchen/mesop-fastapi

It works!

Next steps:

- [ ] Create an actual guide
- [ ] Be able to configure Mesop dev mode as an environmental variable? (seems generally useful for debugging)
- [ ] Hot reloading doesn't work
- [ ] JS file changes doesn't trigger uvicorn reload

**Comment by richard-to** [comment]
Nice, this sounds pretty awesome. This definitely could potentially solve quite a few issues, such as #564 and #472
