### ISSUE TITLE
webcomponent copy_to_clipboard_app fails when accessed externally 

### ISSUE THREAD

**Issue by williamsdoug** [google/mesop#809]
**Describe the bug**
Copy_to_clipboard  component operates as expected when accessed via localhost, but fails to populate clipboard when accessed via external address.  

**To Reproduce**

1. Extract mesop/examples/web_component/copy_to_clipboard/* from mesop git repo
2. edit import statement in copy_to_clipboard_app.py to
```from copy_to_clipboard_component import (copy_to_clipboard_component)```
3. run mesop copy_to_clipboard_app.py 
4. Click on copy icon on browser page
5. paste contents into some editor or other application

**Expected behavior**

 - browser window should include copy icon and sample text
 - after clicking on copy icon, should be able to past text into another app such as editor

When accessed via local url (localhost)
- renders display as expected
- when clicking copy icon, successfully inserts text into past buffer

When accessed via external IP
- renders display as expected
- text NOT inserted into past buffer, paste buffer contents remain unchanged
- error message appears under browser developer mode console

````zone.umd.js:1215 
Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at CopyToClipboard._onClick (copy_to_clipboard_component.js:26:8)
    at ns.handleEvent (lit-html.ts:2102:29)
    at task.callback (zone.umd.js:1156:68)
    at _ZoneDelegate.invokeTask (zone.umd.js:447:37)
    at ZoneImpl.runTask (zone.umd.js:195:51)
    at ZoneTask.invokeTask [as invoke] (zone.umd.js:529:38)
    at invokeTask (zone.umd.js:1165:22)
    at globalCallback (zone.umd.js:1196:31)
    at HTMLDivElement.globalZoneAwareCallback (zone.umd.js:1232:20)  
````

**Screenshots**

**Desktop System Info**

- OS: Ubuntu 22.04.1
- Browser: Chrome 127.0.6533.99
- Version mesop 0.12.0

**Additional context**

**Comment by wwwillchen** [comment]
This looks like a Chrome browser policy - https://stackoverflow.com/a/51823007 - it looks you're accessing the app from an insecure context when using an external ip. You could try deploying the app (e.g. Cloud Run, Hugging Face spaces): https://google.github.io/mesop/guides/deployment/

**Comment by williamsdoug** [comment]
Thanks for the quick response!  I can confirm that following instructions in the provided stackoverflow link addressed the issue.  Specifically I enabled Chrome  "Insecure origins treated as secure"  (via chrome://flags)  for address http://<external_ip_address>:<external:port>
