### ISSUE TITLE
Two pygame window jump out！

### ISSUE THREAD

**Issue by ZhenningLang** [google/mesop#813]
**Describe the bug**
Two pygame window jump out！

![20240821_1](https://github.com/user-attachments/assets/244098b3-68a5-4d8c-ad6a-2ccf8242aea0)

<img width="638" alt="20240821_2" src="https://github.com/user-attachments/assets/f2c6d0af-0eb9-4e0a-abfc-33dfbd7bf0f9">

After a kill -9 operation, the pygrame windows jumped out every time I run
```
mesop mesop_demo.py
``` 

If I accept, mesop seemed to run continuously. (And If I close the opened two pygrame windows, mesop crashed!)

If I reject, mesop would not run. 

**Desktop System Info**

- OS: iOS

**Comment by wwwillchen** [comment]
Can you share your code for `mesop_demo.py`? Are you importing / running pygame in your Mesop code?

**Comment by wwwillchen** [comment]
Closing this - but please feel free to re-open if you add more information requested above
