### ISSUE TITLE
Load image from local pc is imposible, only from an url. How can we do to load an image file from local computer?

### ISSUE THREAD

**Issue by mariano1000** [google/mesop#866]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wwwillchen** [comment]
Once we finish #803 (which'll be in the next release), you should be able to serve local images using standard Python web frameworks.

**Comment by richard-to** [comment]
#803 is now live. So going to close this issue. Also once we have #960, that should make things slightly easier.

**Comment by goran-markovic85** [comment]
Workaround use base64 to convert image and add  html 
```
  me.html(
                    f'<img src="data:image/png;base64,{image_logo}"  alt="" />'
                )
```
