### ISSUE TITLE
CSS injection / external CSS Problem

### ISSUE THREAD

**Issue by anerathil** [google/mesop#886]
Hey guys, 

thank you for the awesome lib! Came here a few days ago while searching for a Streamlit alternative and i really love Mesop, especially the ability to add custom web components with Lit <3

While trying to somehow inject custom CSS into the app i came across @wwwillchen example with loading Mesop into a FastAPI app. I tried this approach to "host" my CSS cause I dont have a CDN available currently.

I ended up with this:

```python
from fastapi import FastAPI
from fastapi.responses import PlainTextResponse
from fastapi.middleware.wsgi import WSGIMiddleware
import mesop as me

FASTAPI_PORT = 8000
FASTAPI_HOST = "0.0.0.0"
app = FastAPI()


@app.get("/custom_styles.css")
def css():
  return PlainTextResponse("""
body {
    background :red;
}

.test {
    background: green;
}
"""
)

app.mount("/", WSGIMiddleware(me))


@me.page(
  path = "/",
  title = "Css Test",
  stylesheets = [
    f"http://{FASTAPI_HOST}:{FASTAPI_PORT}/custom_styles.css"
  ],
)
def test():
    me.set_theme_mode("dark")
    me.html("<div class=\"test\">Test</div>")
    
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("fastapi_injection:app", host = FASTAPI_HOST, port = FASTAPI_PORT, reload=True)

```

**Describe the bug**
Somehow my custom CSS is not getting applied. I was expecting ShadowDom issues, but its not getting applied to anything.
when inspecting the body for example in the Chrome Dev Console, i dont see any "custom_styles.css" in the list of styles applied to the body element.

**Logs**
FastAPI:

> INFO:     127.0.0.1:49780 - "GET /custom_styles.css HTTP/1.1" 200 OK

Curl CSS request:

curl localhost:8000/custom_styles.css

> body {
>     background :red;
> }
> 
> .test {
>     background: green;
> }

Chrome Dev Console:
![image](https://github.com/user-attachments/assets/587d5245-3f92-4134-b36e-3201b3c0d0b5)

Html Tree:
![image](https://github.com/user-attachments/assets/92ccb73c-a8e9-412b-b09c-fe1e48a68aef)

Any ideas whats happening / why it isnt working?

**Comment by richard-to** [comment]
Thanks for the sample code. I tested it out. The issue is you need to set the content type to text/css it seems (at least in chrome).

```
    return PlainTextResponse(
        """
body {
    background :red;
}

.test {
    background: green;
}
""",
        media_type="text/css",
    )
```

One thing to note: Is that the setting the background color on the body doesn't work well since it looks we render another div somewhere that covers the body bad background.

**Comment by anerathil** [comment]
Yay, thanks for the answer :) 

It's working as expected on my side 🎉
![image](https://github.com/user-attachments/assets/575c355c-0cd9-47c4-974b-32ef7c9363af)

**Comment by richard-to** [comment]
Awesome glad it works. I'm definitely excited about being able to use FastAPI with Mesop. Opens up a lot of options.
