### ISSUE TITLE
AI Editor - Demo App - Kind of weird to have two visual editor bars

### ISSUE THREAD

**Issue by richard-to** [google/mesop#910]
It makes sense why there are two editor bars in the demo case due to the iframe.

Side note: also noticed a weird thing where the history menu does not move with the visual editor. Also noticed if I focus on the visual editor, I can press escape, which will close the history menu. But if I drag the editor, then press escape, the history menu does not close.

<img width="1312" alt="Screenshot 2024-08-31 at 1 22 46 PM" src="https://github.com/user-attachments/assets/1e4bb948-ebdf-4d80-a605-42677beb3f55">

**Comment by wwwillchen** [comment]
Yeah, I noticed this too and I'm not sure what's the best way to fix this.

I thought about having a check where if the editor toolbar is in the top-level frame (e.g. the mesop app is not iframed), then we show the editor toolbar, but this would break certain use cases that we may want to support in the future like Colab, IDX, etc. where Mesop is embedded in an in-browser editor/IDE app.

We could do a fancier thing where we try to check the frame hierarchy and if there's any ancestor frame that is a Mesop app (which can show editor toolbar), then we hide it. This seems a bit complicated though and I feel like this Mesop embedding Mesop app is kind of a rare scenario (that we happen to use heavily for the demo gallery).
