### ISSUE TITLE
Unable to run mel.chat with gemini on colab

### ISSUE THREAD

**Issue by richard-to** [google/mesop#921]
I was trying to get a version of this code to run in Colab but it does not work: https://gist.github.com/richard-to/9a72fd7b02a9c3e5eff7d6d3394f911d

No response is ever returned. It does work when I just returned canned text, but does not seem to be able to get a response when using the gemini API.

The code itself works when I run it locally.

I also tried a non-streaming version and it still did not work.

**Comment by wwwillchen** [comment]
Yeah, I hit this issue - the problem is that Colab does some monkey-patching with the Gemini API which interferes with Mesop (because we run the app in a background thread). There's a potential fix I chatted with a Colab team member about. In short, there's not much we can do in Mesop about this.
