### ISSUE TITLE
AI: How to specify paths for prompt fragments?

### ISSUE THREAD

**Issue by richard-to** [google/mesop#956]
This is more of a UX thing, but it was unclear to me how to specify paths for the prompt fragments when using the content path approach.

Do I need to specify a path within the data repo? And is the path relatively to that repo? Or can I specify a file from anywhere?

I did wonder here if using the upload component could be helpful (mostly easier to get the full path of a file and then potentially it could be move to the right location).

Also think in regards to the prompt fragments that they could use a better directory structure as more variations get added.

**Comment by wwwillchen** [comment]
The autocomplete suggests files that are in the data repo prompt_contents dir
(I tried to signify this with the `//prompt_contents/path.txt`, although it is a bit confusing).

I think it could be any path relative to that repo - see https://github.com/google/mesop/blob/2167c548d9e9a52ff7b531df88485b8f33d1fd5e/ai/src/ai/common/executor.py#L220

(It could probably be even outside of the repo, but I don't think I'd recommnd that).

Yeah, I think having an upload component and also a prompt content preview would be helpful
