### ISSUE TITLE
AI: Prompt Versioning for Evals?

### ISSUE THREAD

**Issue by richard-to** [google/mesop#967]
Not 100% sure, but right now it seems like if I updated a prompt fragment(s), these changes will get propagated to other producers. This is slightly problematic for evals, because ideally we'd have a copy of the original prompt/instructions used for the original eval run.

**Comment by wwwillchen** [comment]
yeah, agree - we should probably just do a full copy when the eval gets run.
you (should) be able to figure out the prompt used because everything is version controlled with the mesop-data repo (assuming you commit after every prompt change / before an eval run)
