### ISSUE TITLE
Customize shape of Slide Toggle component

### ISSUE THREAD

**Issue by Hitish99** [google/mesop#969]
**Describe the bug**
I Expected that slide toggle looks can be customized. but I checked and cannot find any configuration which can change height of the component. I tried even density set to -4 is not working on slide toggle. 

**Expected behavior**
I think so some of the styling of slide toggle should be available. Like color, height, width etc

**Comment by richard-to** [comment]
Hi Hitish99. Sorry about the late reply. It's interesting that the slide toggle is not affected by the density setting.

In terms of additional styling options, the Angular component doesn't seem provide any options for doing so.

------

One workaround is to see to include a CSS stylesheet and try to avoid override the slide toggle styling. This can be done by including a stylesheet through the page object. The stylesheet will need to hosted on a separate server. Or you can mount a FastAPI server and host the stylesheet from there.

I'm not 100% sure how much styling you can override though. Haven't tried.

If have any questions on how to specify a stylesheet from the page object or to mount a server with mesop, those should be in our docs here: https://google.github.io/mesop/. You can use the search bar to find those pages.

**Comment by richard-to** [comment]
Going to close this issue. The Angular components API for slide toggle doesn't offer any API for modifying color, height, width. So that prevents us from exposing those styling adjustments.

Best options for now:

1. Try to add a stylesheet to override those styles
2. Create a custom web component to create a custom slide toggle.
