### ISSUE TITLE
Mesop is binding to localhost (127.0.0.1) instead of 0.0.0.0

### ISSUE THREAD

**Issue by architSrivastav** [google/mesop#972]
Problem: 
If i run mesop application in an ec2 instance. if I then try to use the app via ec2-ip:port-number then it does not work. because mesop is bind to localhost instead of 0.0.0.0 

**Describe the solution you'd like**
it should bind to 0.0.0.0 by default

**Comment by richard-to** [comment]
How are you running your Mesop app? Is your ec2 instance more of a dev box or is this a deployment targeting actual users?

If it's the latter, then I think it's recommended to use something like gunicorn (from there you can see the host to bind to). See https://google.github.io/mesop/guides/deployment/

**Comment by architSrivastav** [comment]
Apologies for raising a silly issue. 

We can mark this as resolved now. Thanks a lot!
