### ISSUE TITLE
Mysterious space under some form field components (e.g. Select, Input, Textarea)

### ISSUE THREAD

**Issue by jHimanen** [google/mesop#984]
**Description**
Mesop adds some (unwanted) space beneath components like the ones mentioned in the title. The behaviour does not occur with all components; e.g. Text, Button, and Slider don't display this. This can't be overridden by setting component margins to zero. 

**To Reproduce**
Steps to visibly reproduce the behavior:

1. Add a box to your page and make its borders visible
2. Add an Input element inside the box
3. See the rendered page and spot the space between the input element and the bottom border of the box

**Expected behavior**
No space between the Input element and the bottom border.

**Screenshots**

<img width="553" alt="Screenshot 2024-09-25 at 12 50 11" src="https://github.com/user-attachments/assets/80001b28-42de-4e00-aef2-cb543563ddcf">

The content above was generated like this:
```
@me.page(path="/")
def page():
  with me.box(style=me.Style(
    border=me.Border.all(me.BorderSide(width=2, color="black", style="solid")),
    padding=me.Padding.all(0),
  )):
    me.input(
      label="Test input",
      on_blur=on_test_input_blur,
      style=me.Style(margin=me.Margin.all(0)),
    )
```

**Desktop System Info**

- OS: MacOS Sonoma 14.6.1
- Browser: Chrome

**Additional context**
I went into the generated HTML in the browser, and found that the mysterious space is a `div` element with class `"mat-mdc-form-field-subscript-wrapper mat-mdc-form-field-bottom-align ng-tns-c1534922977-1"`. No idea where it comes from, though.

**Comment by richard-to** [comment]
This looks to be part of the default angular components styling. So in some ways it works as intended.

But I agree it is annoying that we cannot override it in Mesop. The hacky way to do it is to include your own stylesheet and see if you can override it. You can specify a stylesheet to import via the page decorator.

To host the stylesheet you can either mount a Fast API server with Mesop or host the stylesheet from a separate server. Right now we do not have a way to expose a static assets directory (though I think that is doable and we do have a github issue for it somewhere).

**Comment by wwwillchen** [comment]
You can use `subscript_sizing` parameter and set to "dynamic" - see [material docs](https://material.angular.io/components/form-field/api#:~:text=Whether%20the%20form%20field%20should%20reserve%20space%20for%20one%20line%20of%20hint/error%20text%20(default)%20or%20to%20have%20the%20spacing%20grow%20from%200px%20as%20needed%20based%20on%20the%20size%20of%20the%20hint/error%20content.%20Note%20that%20when%20using%20dynamic%20sizing%2C%20layout%20shifts%20will%20occur%20when%20hint/error%20text%20changes.) for details
