### ISSUE TITLE
Add native versions of html elements (checkbox, radio, input, button, etc)

### ISSUE THREAD

**Issue by richard-to** [google/mesop#991]
I think it could be useful to include native versions of those components. That may help being able to control the styling a bit more, much like the native text area.

Main drawback is that it's a bit tedious to add them, so not sure it's worth it to do all of them.

**Comment by wwwillchen** [comment]
Personally, I'd probably just redirect people to building web components if they need this kind of control. I think textarea was the exception because I noticed even Google apps were using a native textarea over the material textarea, but I don't really see this the case with other components.

For example, for things like checkbox, you can't fully style them (the way a lot of UI frameworks would) using our style API because you need advanced CSS selectors. Here's an example from Claude on creating a styled checkbox:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Styled Checkbox</title>
    <style>
        .checkbox-container {
            display: block;
            position: relative;
            padding-left: 35px;
            margin-bottom: 12px;
            cursor: pointer;
            font-size: 18px;
            user-select: none;
        }

        .checkbox-container input {
            position: absolute;
            opacity: 0;
            cursor: pointer;
            height: 0;
            width: 0;
        }

        .checkmark {
            position: absolute;
            top: 0;
            left: 0;
            height: 25px;
            width: 25px;
            background-color: #eee;
            border-radius: 4px;
            transition: all 0.3s;
        }

        .checkbox-container:hover input ~ .checkmark {
            background-color: #ccc;
        }

        .checkbox-container input:checked ~ .checkmark {
            background-color: #2196F3;
        }

        .checkmark:after {
            content: "";
            position: absolute;
            display: none;
        }

        .checkbox-container input:checked ~ .checkmark:after {
            display: block;
        }

        .checkbox-container .checkmark:after {
            left: 9px;
            top: 5px;
            width: 5px;
            height: 10px;
            border: solid white;
            border-width: 0 3px 3px 0;
            transform: rotate(45deg);
        }
    </style>
</head>
<body>
    <label class="checkbox-container">
        Custom Checkbox
        <input type="checkbox" checked="checked">
        <span class="checkmark"></span>
    </label>
</body>
</html>
```

**Comment by richard-to** [comment]
Yeah that's a great point about web components. That makes sense. Probably would be less work to create them too using web components.

I may give it a shot and build out a couple to provide some examples. There seems to be more people asking about adjusting the style of the components lately. 

But also I think having the native versions could be helpful to make integration with third party CSS frameworks work better.

Closing this.
